# checklist_data.py
# All 17 Perfect Delivery stages mapped from SUB-08_C9(Houses) Jul 2023
# item types:
#   "check"          — Yes / No / N/A
#   "text_with_check"— Yes / No / N/A + required text field (spec confirmations)
# photo: True        — photo upload required for this item

STAGES = {
    1: {
        "number": 1,
        "name": "Substructure",
        "short_name": "01 — Substructure",
        "applies_to": "Groundworkers, Bricklayers",
        "items": [
            {"id": "01_01", "text": "Line & level setting out of excavation is correct", "type": "check"},
            {"id": "01_02", "text": "Bottom of excavation is clean", "type": "check"},
            {"id": "01_03", "text": "Correct concrete mix — confirm mix used", "type": "text_with_check", "placeholder": "e.g. C20/25 RC25"},
            {"id": "01_04", "text": "Concrete is placed in the correct temperatures", "type": "check"},
            {"id": "01_05", "text": "Blockwork is fully bedded & finished with all joints full & flush", "type": "check"},
            {"id": "01_06", "text": "Blockwork is level & plumb with datum points from setting out engineer & is the correct height as indicated on drawings", "type": "check"},
            {"id": "01_07", "text": "Internal walls are fully bonded to cavity walls. Wall tie bonding is NOT permitted", "type": "check"},
            {"id": "01_08", "text": "Correct wall ties used & correctly installed. Vertically 450mm, horizontally 750mm. At openings vertically 225mm. Wall tie not falling back into internal blockwork", "type": "check", "photo": True, "photo_label": "Wall ties showing correct alignment"},
            {"id": "01_09", "text": "Blockwork dimensions check — floor beams fit without protruding into cavity & have full wall bearing as designed", "type": "check"},
            {"id": "01_10", "text": "Cavity fill chamfered towards the face brickwork", "type": "check"},
            {"id": "01_11", "text": "Drainage laid to correct falls & bedded & surrounded by shingle or concrete bedded as per contract drawings", "type": "check", "photo": True, "photo_label": "Drainage installation"},
            {"id": "01_12", "text": "DPC installed & lapped under floor planks", "type": "check", "photo": True, "photo_label": "DPC installation and laps"},
            {"id": "01_13", "text": "Ground floor slab installed correctly in accordance with design drawings & correct residue cavity provided", "type": "check"},
            {"id": "01_14", "text": "Air bricks are installed as contract drawings", "type": "check"},
            {"id": "01_15", "text": "Level of concrete slab placed & thresholds installed as PFC standard detail (refer to contract drawings)", "type": "check"},
            {"id": "01_16", "text": "Air bricks are fully bedded, seated & correctly aligned", "type": "check", "photo": True, "photo_label": "Air bricks bedded and aligned"},
            {"id": "01_17", "text": "Service entries are fully finished in accordance with warranty provider's requirements & in correct position", "type": "check", "photo": True, "photo_label": "Service entries finished"},
            {"id": "01_18", "text": "Lintels are in place above service entries, with correct bearing", "type": "check"},
            {"id": "01_19", "text": "All service pipes have caps on", "type": "check"},
            {"id": "01_20", "text": "Mains water pipe through duct is insulated from top of pipe to 1m below ground", "type": "check"},
            {"id": "01_21", "text": "Inspection chambers fitted/protected & aligned correctly", "type": "check", "photo": True, "photo_label": "Inspection chambers"},
            {"id": "01_22", "text": "Good grade of stone fully compacted for back fill & level working platform ready to receive scaffold", "type": "check"},
        ]
    },
    2: {
        "number": 2,
        "name": "Superstructure — DPC to 1st Floor",
        "short_name": "02 — Superstructure (DPC to 1st Floor)",
        "applies_to": "Bricklayers",
        "items": [
            {"id": "02_01", "text": "DPC to top of floor planks & brickwork in accordance with drawings", "type": "check", "photo": True, "photo_label": "DPC to floor planks"},
            {"id": "02_02", "text": "Mortar joints are full & perp ends vertically aligned", "type": "check"},
            {"id": "02_03", "text": "Wall ties installed correctly. Vertically 450mm, horizontally 750mm. At openings vertically 225mm. Wall tie not falling back into internal blockwork", "type": "check", "photo": True, "photo_label": "Wall tie installation"},
            {"id": "02_04", "text": "Insulation installed & tightly fitted without voids & not intruding into cavity. Insulation also covers ground floor slab", "type": "check", "photo": True, "photo_label": "Cavity insulation fitted"},
            {"id": "02_05", "text": "Reveals — margins are even & reveals are vertically aligned. All vertical & horizontal joints are full", "type": "check"},
            {"id": "02_06", "text": "Blockwork finished to a fair face finish & all joints within the cavity are full & flush", "type": "check"},
            {"id": "02_07", "text": "Storey height is correct level (in accordance with contract drawings). Blockwork level under joists", "type": "check"},
            {"id": "02_08", "text": "Separating walls are to robust details (Part L & E Building Regs). Cavities are clean without any excess mortar bridging cavity or wall ties", "type": "check", "photo": True, "photo_label": "Separating wall cavity — clean"},
            {"id": "02_09", "text": "Expansion joints are in the correct place (as per contract drawings) & vertical", "type": "check"},
            {"id": "02_10", "text": "Cavity trays have min 75mm turn-up at stop ends, are free from debris & any holes", "type": "check", "photo": True, "photo_label": "Cavity trays with 75mm turn-up"},
            {"id": "02_11", "text": "Stepped trays are fully bedded & clean within the cavity", "type": "check"},
            {"id": "02_12", "text": "Cavity trays & insulation are free from mortar droppings", "type": "check"},
            {"id": "02_13", "text": "Weep holes at 450mm centres above all openings", "type": "check", "photo": True, "photo_label": "Weep holes above openings"},
            {"id": "02_14", "text": "Weep holes are above lintels but not bedded", "type": "check"},
            {"id": "02_15", "text": "Cavities are of correct & consistent width & all cavities are free from debris or objects", "type": "check"},
            {"id": "02_16", "text": "Correct ties used on separating walls — confirm wall tie type used", "type": "text_with_check", "placeholder": "e.g. Ancon RT2 stainless steel ties"},
            {"id": "02_17", "text": "Cavity closures fixed neatly", "type": "check"},
            {"id": "02_18", "text": "Lateral restraint straps are built in correctly on joists & gables (as contract drawings)", "type": "check", "photo": True, "photo_label": "Lateral restraint straps"},
            {"id": "02_19", "text": "Pennyfarthing stones built in with DPC protective covering & are in the correct location", "type": "check"},
            {"id": "02_20", "text": "Lintels are fully bedded & level", "type": "check"},
            {"id": "02_21", "text": "Padstones correctly placed to ensure steels are placed centrally", "type": "check"},
            {"id": "02_22", "text": "Internal insulated separating walls are covered at end of each lift to stop water penetrating the insulation", "type": "check"},
            {"id": "02_23", "text": "Fire socks installed in accordance with contract drawings", "type": "check", "photo": True, "photo_label": "Fire socks installed"},
            {"id": "02_24", "text": "Lintels & steels have correct bearings", "type": "check"},
            {"id": "02_25", "text": "Temporary protection or patination provided to all installed or visible leadwork", "type": "check"},
            {"id": "02_26", "text": "All external brickwork is free from dust, mortar, debris & any other arising", "type": "check"},
            {"id": "02_27", "text": "PVC lintel covers built into all lintels", "type": "check"},
        ]
    },
    3: {
        "number": 3,
        "name": "Joist",
        "short_name": "03 — Joist",
        "applies_to": "Carpenters",
        "measurements": [
            {"id": "03_mW", "label": "Width (W)", "placeholder": "e.g. 4200mm"},
            {"id": "03_mL", "label": "Length (L)", "placeholder": "e.g. 8600mm"},
            {"id": "03_mH", "label": "Height (H)", "placeholder": "e.g. 2400mm"},
            {"id": "03_mS", "label": "Stairwell dimensions", "placeholder": "e.g. 900 x 2800mm"},
        ],
        "items": [
            {"id": "03_01", "text": "Joists are strictly installed in accordance with the contract design drawings", "type": "check"},
            {"id": "03_02", "text": "All hangers are fully nailed", "type": "check", "photo": True, "photo_label": "Joist hangers fully nailed"},
            {"id": "03_03", "text": "All Z clips are fully nailed", "type": "check", "photo": True, "photo_label": "Z clips fully nailed"},
            {"id": "03_04", "text": "Vertical/horizontal straps have min 8 x fixings", "type": "check", "photo": True, "photo_label": "Strap fixings (min 8 shown)"},
            {"id": "03_05", "text": "All perimeter noggins are installed", "type": "check"},
            {"id": "03_06", "text": "Strongbacks are fully nailed & flush with blockwork", "type": "check"},
            {"id": "03_07", "text": "Noggins are flush with internal blockwork or internal partitions", "type": "check"},
            {"id": "03_08", "text": "All built-in joists have correct bearing", "type": "check"},
            {"id": "03_09", "text": "All joists & beams are straight & level", "type": "check"},
            {"id": "03_10", "text": "Joists are flush with blockwork — not protruding into the cavity", "type": "check", "photo": True, "photo_label": "Joist to blockwork junction"},
            {"id": "03_11", "text": "All flooring is set in 10–15mm from blockwork", "type": "check"},
            {"id": "03_12", "text": "All joints in floor are fully glued", "type": "check"},
            {"id": "03_13", "text": "All tacked nails are removed & holes glued", "type": "check"},
            {"id": "03_14", "text": "Floor perimeter is sealed", "type": "check"},
        ]
    },
    4: {
        "number": 4,
        "name": "Superstructure — 1st Floor to Roof Plate",
        "short_name": "04 — Superstructure (1st Floor to Roof Plate)",
        "applies_to": "Bricklayers",
        "items": [
            {"id": "04_01", "text": "Expansion joints are in the correct place (as per contract drawings) & vertical", "type": "check"},
            {"id": "04_02", "text": "Cavity trays have min 75mm turn-up at stop ends, are free from debris & any holes", "type": "check", "photo": True, "photo_label": "Cavity trays with 75mm turn-up"},
            {"id": "04_03", "text": "All external brickwork is free from dust, mortar, debris & any other arising", "type": "check"},
            {"id": "04_04", "text": "Stepped trays are fully bedded & clean within the cavity", "type": "check"},
            {"id": "04_05", "text": "Cavity trays & insulation are free from mortar droppings", "type": "check"},
            {"id": "04_06", "text": "Weep holes at 450mm centres above all openings", "type": "check", "photo": True, "photo_label": "Weep holes above openings"},
            {"id": "04_07", "text": "Weep holes are above lintels but not bedded", "type": "check"},
            {"id": "04_08", "text": "Cavities are of correct & consistent width & all cavities are free from debris or objects", "type": "check"},
            {"id": "04_09", "text": "Correct ties used on separating walls — confirm wall tie type used", "type": "text_with_check", "placeholder": "e.g. Ancon RT2 stainless steel ties"},
            {"id": "04_10", "text": "Cavity closures fixed neatly", "type": "check"},
            {"id": "04_11", "text": "Lateral restraint straps are built in correctly on joists & gables (as contract drawings)", "type": "check", "photo": True, "photo_label": "Lateral restraint straps"},
            {"id": "04_12", "text": "Pennyfarthing stones built in with DPC protective covering & are in the correct location", "type": "check"},
            {"id": "04_13", "text": "Lintels are fully bedded & level", "type": "check"},
            {"id": "04_14", "text": "Padstones correctly placed to ensure steels are placed centrally", "type": "check"},
            {"id": "04_15", "text": "Insulation installed & tightly fitted without voids & not intruding into cavity", "type": "check", "photo": True, "photo_label": "Cavity insulation fitted"},
            {"id": "04_16", "text": "Reveals — margins are even & reveals are vertically aligned. All vertical & horizontal joints are full", "type": "check"},
            {"id": "04_17", "text": "Blockwork finished to a fair face finish & all joints within the cavity are full & flush", "type": "check"},
            {"id": "04_18", "text": "Storey height is correct level (in accordance with contract drawings). Blockwork level under joists", "type": "check"},
            {"id": "04_19", "text": "Separating walls are to robust details (Part L & E Building Regs). Cavities are clean without any excess mortar bridging cavity or wall ties", "type": "check", "photo": True, "photo_label": "Separating wall cavity — clean"},
            {"id": "04_20", "text": "Mortar joints are full & perp ends vertically aligned", "type": "check"},
            {"id": "04_21", "text": "Wall ties installed correctly. Vertically 450mm, horizontally 750mm. At openings vertically 225mm. Wall tie not falling back into internal blockwork", "type": "check", "photo": True, "photo_label": "Wall tie installation"},
            {"id": "04_22", "text": "PVC lintel covers built into all lintels", "type": "check"},
            {"id": "04_23", "text": "Internal insulated separating walls covered at end of each lift to stop water penetrating the insulation", "type": "check"},
            {"id": "04_24", "text": "Fire socks installed in accordance with contract drawings", "type": "check", "photo": True, "photo_label": "Fire socks installed"},
            {"id": "04_25", "text": "Lintels & steels have correct bearings", "type": "check"},
            {"id": "04_26", "text": "Temporary protection or patination provided to all installed or visible leadwork", "type": "check"},
        ]
    },
    5: {
        "number": 5,
        "name": "Roof Structure",
        "short_name": "05 — Roof Structure",
        "applies_to": "Carpenters",
        "items": [
            {"id": "05_01", "text": "No damaged trusses or spandrel pads exist", "type": "check"},
            {"id": "05_02", "text": "Trusses installed as contract drawing", "type": "check", "photo": True, "photo_label": "Overview of truss installation"},
            {"id": "05_03", "text": "All truss clips are fitted, including girder truss clips", "type": "check", "photo": True, "photo_label": "Truss clips fitted"},
            {"id": "05_04", "text": "All clips/shoes/hangers are fully nailed", "type": "check", "photo": True, "photo_label": "Clips/shoes/hangers fully nailed"},
            {"id": "05_05", "text": "All bracing has 2 x nails per truss", "type": "check", "photo": True, "photo_label": "Bracing with 2 nails per truss"},
            {"id": "05_06", "text": "All bracing is installed to manufacturers instructions", "type": "check"},
            {"id": "05_07", "text": "Diagonal bracing fixed to plate or lowest node point on truss", "type": "check"},
            {"id": "05_08", "text": "All bracing flush with internal blockwork", "type": "check", "photo": True, "photo_label": "Bracing flush with blockwork"},
            {"id": "05_09", "text": "All horizontal bracing is flush with internal blockwork", "type": "check"},
            {"id": "05_10", "text": "All straps have a minimum of 8 fixings & correctly positioned", "type": "check", "photo": True, "photo_label": "Strap fixings (min 8 shown)"},
            {"id": "05_11", "text": "All trusses are level & plumb", "type": "check"},
            {"id": "05_12", "text": "Plate straps are fixed in accordance with engineers drawings", "type": "check", "photo": True, "photo_label": "Plate straps fixed"},
            {"id": "05_13", "text": "Gable ladders are fixed & propped", "type": "check", "photo": True, "photo_label": "Gable ladders fixed and propped"},
            {"id": "05_14", "text": "Girder trusses are nailed together to manufacturers specification", "type": "check"},
            {"id": "05_15", "text": "No gang nail plates are missing or damaged", "type": "check"},
            {"id": "05_16", "text": "Valley trusses are supported underneath with a brace/tilt fillet", "type": "check", "photo": True, "photo_label": "Valley truss support"},
            {"id": "05_17", "text": "Spandrel panels are plumb, all joints/holes have intumescent mastic & are over boarded", "type": "check", "photo": True, "photo_label": "Spandrel panels with mastic"},
            {"id": "05_18", "text": "Spandrels are sat on Rockwool & strapped to party wall", "type": "check", "photo": True, "photo_label": "Spandrel to party wall junction"},
            {"id": "05_19", "text": "Hips & jack rafters are fully nailed", "type": "check"},
            {"id": "05_20", "text": "All fascias & soffits are straight, fascias double nailed & soffits nailed to soffit supports", "type": "check"},
            {"id": "05_21", "text": "Soffit cradles are in every other truss as a minimum", "type": "check"},
            {"id": "05_22", "text": "Soffit voids are filled with fire sock at party wall junctions", "type": "check", "photo": True, "photo_label": "Fire sock at soffit/party wall"},
            {"id": "05_23", "text": "All fascia & soffit bargeboard corner/joint trims are installed & fixed", "type": "check"},
            {"id": "05_24", "text": "All soffits are cleaned out", "type": "check"},
            {"id": "05_25", "text": "All storage boards correctly installed as contract drawings", "type": "check"},
            {"id": "05_26", "text": "All cavities have fire socks installed in correct locations and in accordance with the drawings", "type": "check", "photo": True, "photo_label": "Cavity fire socks in place"},
            {"id": "05_27", "text": "Rockwool fire check to party walls to continue into soffit zone", "type": "check", "photo": True, "photo_label": "Rockwool fire check at party wall/soffit"},
            {"id": "05_28", "text": "All rainwater goods installed to correct falls and height & fully tested", "type": "check", "photo": True, "photo_label": "Rainwater goods installed"},
            {"id": "05_29", "text": "Plate halved, fully bedded & nailed", "type": "check"},
            {"id": "05_30", "text": "Plate straps in place & fixed every 150mm", "type": "check"},
            {"id": "05_31", "text": "All bed joints & perps fully filled", "type": "check"},
            {"id": "05_32", "text": "Joists blocked, filled & mastic on party walls", "type": "check", "photo": True, "photo_label": "Joists blocked and mastic at party wall"},
        ]
    },
    6: {
        "number": 6,
        "name": "Roof Tiling",
        "short_name": "06 — Roof Tiling",
        "applies_to": "Roof Tilers",
        "items": [
            {"id": "06_01", "text": "Fire separation installed to underside of sarking felt, between each batten & continuing through to back of fascia board", "type": "check", "photo": True, "photo_label": "Fire separation at eaves"},
            {"id": "06_02", "text": "Eaves support trays installed & fixed in accordance with manufacturer's fixing recommendations", "type": "check"},
            {"id": "06_03", "text": "Felt laid straight & 10mm drapes are continuous between rafters", "type": "check"},
            {"id": "06_04", "text": "Horizontal laps are 150mm minimum", "type": "check", "photo": True, "photo_label": "Felt horizontal lap measurement"},
            {"id": "06_05", "text": "Vertical laps are 100mm minimum and coincide with a rafter", "type": "check"},
            {"id": "06_06", "text": "Where dry verges are used — underlay overhangs the verge as specified by tile manufacturer", "type": "check"},
            {"id": "06_07", "text": "For dry ridge systems — underlay terminates below the apex as specified by manufacturer", "type": "check"},
            {"id": "06_08", "text": "At hip level — underlay overlaps at the hip line by at least 150mm", "type": "check"},
            {"id": "06_09", "text": "At valleys — underlay overlaps at centre line by minimum 300mm (or 600mm continuous strip along valley)", "type": "check", "photo": True, "photo_label": "Valley underlay overlap"},
            {"id": "06_10", "text": "All tiles are without defects, chips or heavy scratches", "type": "check"},
            {"id": "06_11", "text": "At side & top abutments — underlay turned up the vertical surface by 50mm", "type": "check"},
            {"id": "06_12", "text": "At back abutments — underlay overlaps the material forming the back abutment by 150mm", "type": "check"},
            {"id": "06_13", "text": "Where pipes penetrate underlay — neatly cut a cross & underlay turned up to give a tight, water shedding fit", "type": "check", "photo": True, "photo_label": "Pipe penetration through underlay"},
            {"id": "06_14", "text": "Battens are nailed into each rafter (minimum nail size 65 x 3.35mm)", "type": "check"},
            {"id": "06_15", "text": "No batten smaller than 1200mm long & fixed parallel with eaves & ridge line", "type": "check"},
            {"id": "06_16", "text": "No more than one joint evident in any four consecutive battens", "type": "check"},
            {"id": "06_17", "text": "All batten cut ends are square and the joist is located over a rafter", "type": "check"},
            {"id": "06_18", "text": "All batten ends are splay nailed", "type": "check"},
            {"id": "06_19", "text": "All batten ends are supported at hips & valleys", "type": "check"},
            {"id": "06_20", "text": "First batten at eaves fixed to achieve 45–55mm overhang or centre of gutter", "type": "check"},
            {"id": "06_21", "text": "Last ridge battens set so ridge tiles overlap top course of tiles by at least 75mm", "type": "check"},
            {"id": "06_22", "text": "Every tile is mechanically fixed", "type": "check", "photo": True, "photo_label": "Mechanical tile fixings"},
            {"id": "06_23", "text": "Fixing nails used — confirm nail type", "type": "text_with_check", "placeholder": "e.g. Copper / Stainless Steel / Silicon Bronze"},
            {"id": "06_24", "text": "All tiles fixed in accordance with site specific specification — confirm gauge & headlap", "type": "text_with_check", "placeholder": "e.g. Gauge: 100mm, Headlap: 75mm"},
            {"id": "06_25", "text": "Lead flashings, aprons, gutters, valley and saddles fitted in accordance with BLM (British Lead Manufacturers) basic fitting guides", "type": "check", "photo": True, "photo_label": "Lead flashings/aprons fitted"},
            {"id": "06_26", "text": "Roof is left clean with no debris/dust on the surface or fittings", "type": "check", "photo": True, "photo_label": "Completed roof — clean overview"},
        ]
    },
    7: {
        "number": 7,
        "name": "Carpentry 1st Fix",
        "short_name": "07 — Carpentry 1st Fix",
        "applies_to": "Carpenters",
        "items": [
            {"id": "07_01", "text": "All stairwell studwork is CLS timber and installed in accordance with the drawings", "type": "check", "photo": True, "photo_label": "Stairwell studwork"},
            {"id": "07_02", "text": "Window boards are in place with correct length of returns in accordance with the contract specification", "type": "check"},
            {"id": "07_03", "text": "All window boards are square — line & level checked", "type": "check"},
            {"id": "07_04", "text": "Window boards level & wings correct length & sanded", "type": "check"},
            {"id": "07_05", "text": "All pattresses in place & fixed", "type": "check", "photo": True, "photo_label": "Pattresses fixed"},
            {"id": "07_06", "text": "All door linings fixed with 8 screws either side — line & level checked", "type": "check", "photo": True, "photo_label": "Door lining fixings"},
            {"id": "07_07", "text": "All stairs fitted with adequate fixings, treads do not squeak & have even margins on string", "type": "check", "photo": True, "photo_label": "Stair installation"},
            {"id": "07_08", "text": "Stair treads protected, hand rails & newel posts in place where required", "type": "check", "photo": True, "photo_label": "Stair protection and handrails"},
        ]
    },
    8: {
        "number": 8,
        "name": "Electrical 1st Fix",
        "short_name": "08 — Electrical 1st Fix",
        "applies_to": "Electricians",
        "items": [
            {"id": "08_01", "text": "All power & lighting cables installed to circuit chart — vertical & horizontal, not diagonal", "type": "check", "photo": True, "photo_label": "Cable routing (vertical/horizontal)"},
            {"id": "08_02", "text": "All electrical fittings installed in accordance with the house type electrical plan", "type": "check"},
            {"id": "08_03", "text": "Grommets & pattress boxes fitted", "type": "check"},
            {"id": "08_04", "text": "All electric boxes securely fixed & in line", "type": "check", "photo": True, "photo_label": "Back boxes aligned"},
            {"id": "08_05", "text": "All cables to consumer unit are taped as requested", "type": "check"},
            {"id": "08_06", "text": "No smoke/heat detectors within 300mm zone of window, door opening or trap hatch", "type": "check"},
            {"id": "08_07", "text": "All elec/BT/TV cables installed", "type": "check"},
            {"id": "08_08", "text": "Sub main cable installed — glanded into position", "type": "check"},
            {"id": "08_09", "text": "All back boxes & containment/capping complete. Metal back boxes used", "type": "check", "photo": True, "photo_label": "Back boxes and capping complete"},
            {"id": "08_10", "text": "Metal fixings in place in ceilings", "type": "check"},
            {"id": "08_11", "text": "Cables in boxes taped over", "type": "check"},
            {"id": "08_12", "text": "Ducting/core holes complete — ducting foil taped & sealed", "type": "check", "photo": True, "photo_label": "Ducting/core holes sealed"},
        ]
    },
    9: {
        "number": 9,
        "name": "Plumbing 1st Fix",
        "short_name": "09 — Plumbing 1st Fix",
        "applies_to": "Plumbers",
        "items": [
            {"id": "09_01", "text": "Plastic pipework on blockwork walls has metal tape applied & positioned in corners, not next to windows", "type": "check"},
            {"id": "09_02", "text": "All internal pipework has been tested under pressure", "type": "check", "photo": True, "photo_label": "Pressure gauge during test"},
            {"id": "09_03", "text": "Pressure test has been monitored (daily) & signed off by the plumber", "type": "check"},
            {"id": "09_04", "text": "Hot & cold pipes have blue & red tape applied & are capped off", "type": "check", "photo": True, "photo_label": "Hot/cold pipe identification"},
            {"id": "09_05", "text": "Gas supply pipework fitted correctly to avoid fouling kitchen units", "type": "check"},
            {"id": "09_06", "text": "All pipes are clipped sufficiently", "type": "check"},
            {"id": "09_07", "text": "SVPs are adequately fixed with plugs & screws", "type": "check", "photo": True, "photo_label": "SVP fixings"},
            {"id": "09_08", "text": "Underfloor heating actuator matches stats", "type": "check"},
            {"id": "09_09", "text": "All underfloor heating valves are open", "type": "check", "photo": True, "photo_label": "UFH manifold with valves open"},
            {"id": "09_10", "text": "Underfloor heating checked for leaks & air", "type": "check", "photo": True, "photo_label": "UFH pressure test"},
            {"id": "09_11", "text": "All copper pipes that could knock when expanded have hair felt fitted to avoid expansion noises", "type": "check"},
            {"id": "09_12", "text": "Soils tested", "type": "check", "photo": True, "photo_label": "Soil test result"},
            {"id": "09_13", "text": "WC cold fill is installed", "type": "check"},
            {"id": "09_14", "text": "Shower trays are installed in accordance with the contract specification", "type": "check", "photo": True, "photo_label": "Shower tray installation"},
            {"id": "09_15", "text": "Waste run under shower tray is sealed with no leaks", "type": "check", "photo": True, "photo_label": "Waste under shower tray — sealed"},
        ]
    },
    10: {
        "number": 10,
        "name": "Pre-Plaster",
        "short_name": "10 — Pre-Plaster",
        "applies_to": "Site Manager / Team",
        "room_based": True,
        "rooms": ["Hall", "Cloaks", "Lounge", "Dining", "Kitchen", "Utility", "Rec 3", "Stairs", "Landing", "Bed 1", "Bed 2", "Bed 3"],
        "items": [
            {"id": "10_01", "text": "10mm gap maintained to perimeter of the floor", "type": "check", "photo": True, "photo_label": "Floor perimeter gap"},
            {"id": "10_02", "text": "Party wall has had parge coat applied correctly", "type": "check", "photo": True, "photo_label": "Parge coat applied"},
            {"id": "10_03", "text": "Blockwork joints are full with no holes, gaps or missing blocks throughout the internal blockwork", "type": "check"},
            {"id": "10_04", "text": "No holes evident within the roofing sarking felt & all penetrations through the roof are sealed", "type": "check", "photo": True, "photo_label": "Roof penetrations sealed"},
            {"id": "10_05", "text": "All penetrations that pass through blockwork are sealed", "type": "check", "photo": True, "photo_label": "Blockwork penetrations sealed"},
            {"id": "10_06", "text": "All pattresses in place & fixed", "type": "check"},
            {"id": "10_07", "text": "Stud walls strictly installed in accordance with contract design drawings", "type": "check"},
            {"id": "10_08", "text": "All stud installed to line & level", "type": "check"},
            {"id": "10_09", "text": "Stud fixed as per manufacturer's fixing recommendations", "type": "check"},
            {"id": "10_10", "text": "Timber sole plates, head plates, frame noggins/fixings installed as per manufacturer's recommendations", "type": "check"},
            {"id": "10_11", "text": "All pattress plates installed for all wall fixtures throughout the property", "type": "check"},
            {"id": "10_12", "text": "2m rule clearance from stairs to bulkhead", "type": "check"},
            {"id": "10_13", "text": "Timber base plate to the metal studwork has been installed", "type": "check", "photo": True, "photo_label": "Metal stud base plate installed"},
            {"id": "10_14", "text": "Plot cleaned out & all protection applied to surfaces", "type": "check"},
        ]
    },
    11: {
        "number": 11,
        "name": "Post-Plaster",
        "short_name": "11 — Post-Plaster",
        "applies_to": "Plasterers",
        "room_based": True,
        "rooms": ["Hall", "Cloaks", "Lounge", "Dining", "Kitchen", "Utility", "Rec 3", "Stairs", "Landing", "Bed 1", "Bed 2", "Bed 3", "Bed 4"],
        "items": [
            {"id": "11_01", "text": "All plaster smooth without any rough surfaces & without any undulations", "type": "check", "photo": True, "photo_label": "Finished plaster surface"},
            {"id": "11_02", "text": "All electric boxes are clean — perimeter cut out without excess plaster to edges", "type": "check"},
            {"id": "11_03", "text": "All windows cleaned & free from plaster staining or excess plaster", "type": "check"},
            {"id": "11_04", "text": "Loft insulation is in place & to the correct specification", "type": "check", "photo": True, "photo_label": "Loft insulation"},
            {"id": "11_05", "text": "Sound insulation installed & fitted with no voids", "type": "check", "photo": True, "photo_label": "Sound insulation — no voids"},
            {"id": "11_06", "text": "All plasterboard installed as contract design drawings, fixings as per manufacturer's recommendations", "type": "check"},
            {"id": "11_07", "text": "Correct specification/colour plasterboard used — moisture resistant & fireline board where required", "type": "check"},
            {"id": "11_08", "text": "Drylining installed to line & level", "type": "check"},
            {"id": "11_09", "text": "Staggered plasterboard joints above doors & ceilings. Staggered screws to prevent crimping & splitting of boards", "type": "check", "photo": True, "photo_label": "Staggered plasterboard joints"},
            {"id": "11_10", "text": "All frames & surfaces washed down & areas cleared", "type": "check"},
            {"id": "11_11", "text": "All joints taped", "type": "check", "photo": True, "photo_label": "Taped joints"},
            {"id": "11_12", "text": "All walls finished to a smooth & uniform skimmed finish", "type": "check", "photo": True, "photo_label": "Finished skim coat"},
        ]
    },
    12: {
        "number": 12,
        "name": "Ceramic Tiling",
        "short_name": "12 — Ceramic Tiling",
        "applies_to": "Ceramic Tilers",
        "items": [
            {"id": "12_01", "text": "Floor grout colour as specified — confirm colour used", "type": "text_with_check", "placeholder": "e.g. Mapei Keracolor S Grey"},
            {"id": "12_02", "text": "Floor tile spacing consistent width (up to 5mm wide)", "type": "check"},
            {"id": "12_03", "text": "Variations in surface level between adjacent tiles: max 1mm for joints less than 6mm wide", "type": "check"},
            {"id": "12_04", "text": "No visible cut edges to trims", "type": "check"},
            {"id": "12_05", "text": "Full length trims used", "type": "check"},
            {"id": "12_06", "text": "Floor tiles finished at door side of door stop", "type": "check"},
            {"id": "12_07", "text": "Tile colour consistent — only one batch used", "type": "check"},
            {"id": "12_08", "text": "Spare tiles left for customer/repairs", "type": "check"},
            {"id": "12_09", "text": "Overall variation in surface level: ±3mm maximum deviation from a 2m straight edge with equal offsets", "type": "check"},
            {"id": "12_10", "text": "Wall grout colour as specified — confirm colour used", "type": "text_with_check", "placeholder": "e.g. Mapei Keracolor S White"},
            {"id": "12_11", "text": "Joints straight & aligned", "type": "check", "photo": True, "photo_label": "Wall tile alignment"},
            {"id": "12_12", "text": "Wall tile spacing consistent width (3–5mm wide)", "type": "check"},
            {"id": "12_13", "text": "Floor tiling to correct locations", "type": "check", "photo": True, "photo_label": "Floor tiling layout"},
            {"id": "12_14", "text": "Anti-crack matting installed", "type": "check", "photo": True, "photo_label": "Anti-crack matting"},
            {"id": "12_15", "text": "Wall tiling to correct locations & heights", "type": "check", "photo": True, "photo_label": "Wall tiling heights"},
            {"id": "12_16", "text": "Trims to specified colour — confirm trim colour", "type": "text_with_check", "placeholder": "e.g. Chrome / Matt Black / White"},
        ]
    },
    13: {
        "number": 13,
        "name": "Electrical 2nd Fix",
        "short_name": "13 — Electrical 2nd Fix",
        "applies_to": "Electricians",
        "items": [
            {"id": "13_01", "text": "All sockets/switches/light fittings checked for scratches, screwed back, level & tightened", "type": "check", "photo": True, "photo_label": "Sockets and switches installed"},
            {"id": "13_02", "text": "Light fittings/downlights installed with lamps", "type": "check", "photo": True, "photo_label": "Light fittings with lamps"},
            {"id": "13_03", "text": "All pendants screwed up, sockets/switches screwed back", "type": "check"},
            {"id": "13_04", "text": "Kitchen works complete — grid switch & appliance sockets", "type": "check", "photo": True, "photo_label": "Kitchen electrical works"},
            {"id": "13_05", "text": "Earth bonding complete", "type": "check", "photo": True, "photo_label": "Earth bonding"},
            {"id": "13_06", "text": "Heating system fitted & completed", "type": "check"},
            {"id": "13_07", "text": "Consumer unit & sub mains (if needed) complete", "type": "check", "photo": True, "photo_label": "Consumer unit complete"},
            {"id": "13_08", "text": "Surge protection device fitted", "type": "check", "photo": True, "photo_label": "Surge protection device"},
        ]
    },
    14: {
        "number": 14,
        "name": "Plumbing 2nd Fix",
        "short_name": "14 — Plumbing 2nd Fix",
        "applies_to": "Plumbers",
        "items": [
            {"id": "14_01", "text": "Boiler hot & cold connections are fitted correctly", "type": "check", "photo": True, "photo_label": "Boiler connections"},
            {"id": "14_02", "text": "Heating pump valves are open", "type": "check"},
            {"id": "14_03", "text": "Heating manifold is open with no leaks", "type": "check", "photo": True, "photo_label": "Heating manifold"},
            {"id": "14_04", "text": "Heating bypass valve checked & adjusted to suit the system installed", "type": "check"},
            {"id": "14_05", "text": "Cylinder checked for leaks", "type": "check"},
            {"id": "14_06", "text": "Cylinder blow down checked", "type": "check"},
            {"id": "14_07", "text": "Cylinder benchmark book filled out & label on cylinder", "type": "check", "photo": True, "photo_label": "Cylinder benchmark book and label"},
            {"id": "14_08", "text": "Utility sink overflow connection is correct and not leaking", "type": "check"},
            {"id": "14_09", "text": "Boiler has no leaks — gas & water", "type": "check", "photo": True, "photo_label": "Boiler installation"},
            {"id": "14_10", "text": "Boiler flow & returns are correctly fitted", "type": "check"},
            {"id": "14_11", "text": "Boiler flues are fitted correctly", "type": "check", "photo": True, "photo_label": "Boiler flue"},
            {"id": "14_12", "text": "Adequate brackets fitted to boiler flue in roof space (where applicable). Flues align on terraced/semi-detached houses", "type": "check", "photo": True, "photo_label": "Flue brackets in roof space"},
            {"id": "14_13", "text": "Rads — vent rad flow & return are open", "type": "check"},
            {"id": "14_14", "text": "Rads — TRV is operational", "type": "check"},
            {"id": "14_15", "text": "Rads — flow & return are not crossed", "type": "check"},
            {"id": "14_16", "text": "Vent rad checked & operational", "type": "check"},
            {"id": "14_17", "text": "Washing machine cycle run — no leaks", "type": "check", "photo": True, "photo_label": "Washing machine connections"},
            {"id": "14_18", "text": "Cistern is level", "type": "check"},
            {"id": "14_19", "text": "Shower door alignment fitting is secure. Shower tray has been sealed", "type": "check", "photo": True, "photo_label": "Shower door aligned and tray sealed"},
            {"id": "14_20", "text": "Blending valve is fitted correctly", "type": "check"},
            {"id": "14_21", "text": "Bath overflow installed correctly and does not leak", "type": "check"},
            {"id": "14_22", "text": "Toilet pan is fixed to the wall & floor", "type": "check", "photo": True, "photo_label": "Toilet pan fixings"},
            {"id": "14_23", "text": "Showers — hot & cold feed are correctly fitted", "type": "check"},
            {"id": "14_24", "text": "Basin — hot & cold feeds are correctly fitted", "type": "check"},
            {"id": "14_25", "text": "Position & height of outside taps in accordance with drawings", "type": "check"},
            {"id": "14_26", "text": "Roof space vents are connected", "type": "check", "photo": True, "photo_label": "Roof space vents connected"},
            {"id": "14_27", "text": "Roof space durgos are operational/completed", "type": "check"},
            {"id": "14_28", "text": "No leaks exist to all waste pipes & traps", "type": "check", "photo": True, "photo_label": "Waste pipes and traps — no leaks"},
        ]
    },
    15: {
        "number": 15,
        "name": "Pre-Decoration",
        "short_name": "15 — Pre-Decoration",
        "applies_to": "Site Manager / Team",
        "room_based": True,
        "rooms": ["Hall", "Cloaks", "Lounge", "Dining", "Kitchen", "Utility", "Rec 3", "Stairs", "Landing", "Bed 1", "Bed 2", "Bed 3", "Bed 4"],
        "items": [
            {"id": "15_01", "text": "Hinge cut-outs & all screws fitted, & primed behind hinges (doors)", "type": "check", "photo": True, "photo_label": "Door hinge priming"},
            {"id": "15_02", "text": "Door furniture fitted, aligned & latched", "type": "check"},
            {"id": "15_03", "text": "Skirting scribed & mitred — no large gaps more than 1mm & primed", "type": "check", "photo": True, "photo_label": "Skirting joints"},
            {"id": "15_04", "text": "Architrave mitred — no large gaps more than 1mm & primed", "type": "check", "photo": True, "photo_label": "Architrave joints"},
            {"id": "15_05", "text": "Margins on doors do not exceed 2mm & double doors fully align", "type": "check"},
            {"id": "15_06", "text": "Plot cleaned & doors protected", "type": "check"},
            {"id": "15_07", "text": "Dowels cut off & sanded", "type": "check"},
            {"id": "15_08", "text": "All stair caps/spindles fitted — no large margins exceeding 1mm", "type": "check", "photo": True, "photo_label": "Stair spindles/caps"},
            {"id": "15_09", "text": "Holes around pipes filled and made good", "type": "check", "photo": True, "photo_label": "Pipe holes made good"},
        ]
    },
    16: {
        "number": 16,
        "name": "External Works",
        "short_name": "16 — External Works",
        "applies_to": "Groundworkers, Landscapers",
        "items": [
            {"id": "16_01", "text": "Topsoil laid level ready to receive turf", "type": "check", "photo": True, "photo_label": "Topsoil laid"},
            {"id": "16_02", "text": "Turf not extending above hardstandings", "type": "check"},
            {"id": "16_03", "text": "No gaps or voids present between edgings & hardstanding", "type": "check"},
            {"id": "16_04", "text": "Level access provided in accordance with Part M Building Regs. Approach routes minimum 900mm clear width. Gradient between 1:20 & 1:12", "type": "check"},
            {"id": "16_05", "text": "All drainage covers are flush with hardstanding surface, painted black & all screws provided", "type": "check", "photo": True, "photo_label": "Drainage covers flush with hardstanding"},
            {"id": "16_06", "text": "All gullies are level and fully aligned with the hardstanding, with clean grates", "type": "check", "photo": True, "photo_label": "Gullies level and aligned"},
            {"id": "16_07", "text": "Door threshold drainage installed & free from defects & debris", "type": "check"},
            {"id": "16_08", "text": "All hardstandings have a flat surface without undulations, ridges or defective surface", "type": "check", "photo": True, "photo_label": "Hardstanding surface"},
            {"id": "16_09", "text": "All hardstanding pointing to joints are full & flush with no staining to adjacent surfaces", "type": "check"},
            {"id": "16_10", "text": "All edgings are aligned, without defects or chips & fully bedded on a foundation of concrete with concrete haunching both sides", "type": "check", "photo": True, "photo_label": "Edgings aligned and haunched"},
            {"id": "16_11", "text": "Block paviours laid in accordance with PFC specification, fully compacted, with pattern aligned and fully sanded", "type": "check", "photo": True, "photo_label": "Block paviours — compacted and sanded"},
        ]
    },
    17: {
        "number": 17,
        "name": "Pre-Handover",
        "short_name": "17 — Pre-Handover",
        "applies_to": "Site Manager / Team",
        "room_based": True,
        "rooms": ["Hall", "Cloaks", "Lounge", "Dining", "Kitchen", "Utility", "Rec 3", "Stairs", "Landing", "Bed 1", "Bed 2", "Bed 3"],
        "items": [
            {"id": "17_01", "text": "Fire egress windows are all operational", "type": "check", "photo": True, "photo_label": "Fire egress windows operational"},
            {"id": "17_02", "text": "Glass is free from scratches", "type": "check", "photo": True, "photo_label": "Glass — confirm scratch-free"},
            {"id": "17_03", "text": "All doors close & are fully aligned & don't rattle", "type": "check"},
            {"id": "17_04", "text": "All internal mastic is completed", "type": "check", "photo": True, "photo_label": "Internal mastic complete"},
            {"id": "17_05", "text": "All wet areas have extraction and are operational", "type": "check"},
            {"id": "17_06", "text": "All sanitaryware is free from damage and operational", "type": "check", "photo": True, "photo_label": "Sanitaryware — damage-free"},
            {"id": "17_07", "text": "All isolation valves are operational", "type": "check"},
            {"id": "17_08", "text": "Loft insulation is in place and to the correct specification", "type": "check", "photo": True, "photo_label": "Loft insulation"},
            {"id": "17_09", "text": "All ducting fixed", "type": "check", "photo": True, "photo_label": "Ducting fixed"},
            {"id": "17_10", "text": "Spindles do not exceed 100mm spacing", "type": "check", "photo": True, "photo_label": "Spindle spacing (max 100mm)"},
            {"id": "17_11", "text": "Windows below 800mm have guard rails with spacings not exceeding 100mm", "type": "check", "photo": True, "photo_label": "Window guard rails"},
            {"id": "17_12", "text": "All smoke & heat detectors are linked & min 300mm away from any opening", "type": "check", "photo": True, "photo_label": "Smoke/heat detectors positioned"},
            {"id": "17_13", "text": "All lights are fully operational", "type": "check"},
            {"id": "17_14", "text": "All radiators level, with no pipes showing below the radiator", "type": "check"},
            {"id": "17_15", "text": "Consumer unit is labelled & filled out", "type": "check", "photo": True, "photo_label": "Labelled consumer unit"},
            {"id": "17_16", "text": "All blank plates are on consumer unit", "type": "check"},
            {"id": "17_17", "text": "'Next Inspection' sticker applied & complete to consumer unit", "type": "check"},
            {"id": "17_18", "text": "Electrical certificate issued", "type": "check", "photo": True, "photo_label": "Electrical certificate"},
            {"id": "17_19", "text": "Boiler benchmark book completed", "type": "check", "photo": True, "photo_label": "Completed benchmark book"},
            {"id": "17_20", "text": "Boiler shows installers details", "type": "check", "photo": True, "photo_label": "Boiler installer details label"},
            {"id": "17_21", "text": "Expansion pipes have cage & pipe correctly installed to prevent damage to persons", "type": "check", "photo": True, "photo_label": "Expansion pipe cage installed"},
            {"id": "17_22", "text": "All airing cupboard pipework labelled", "type": "check", "photo": True, "photo_label": "Labelled airing cupboard pipework"},
            {"id": "17_23", "text": "Stop cocks labelled", "type": "check", "photo": True, "photo_label": "Labelled stop cocks"},
            {"id": "17_24", "text": "Air test passed", "type": "check", "photo": True, "photo_label": "Air test certificate/result"},
            {"id": "17_25", "text": "Unit is clean & snagged", "type": "check"},
            {"id": "17_26", "text": "External worksheet complete", "type": "check"},
            {"id": "17_27", "text": "CRC ready — signed and confirmed by the Site Manager", "type": "check"},
        ]
    },
}


def get_stage(number: int) -> dict:
    return STAGES.get(number)


def get_all_stages_summary() -> list:
    """Return lightweight list of stages for the form selector."""
    return [
        {
            "number": s["number"],
            "short_name": s["short_name"],
            "applies_to": s["applies_to"],
        }
        for s in STAGES.values()
    ]


def photo_items_for_stage(stage_number: int) -> list:
    """Return list of items that require a photo in a given stage."""
    stage = STAGES.get(stage_number, {})
    return [i for i in stage.get("items", []) if i.get("photo")]
