# checklist_data.py
# 37 Perfect Delivery milestone stages — Pennyfarthing Homes
# All items follow NHBC guidance and Pennyfarthing site standards
# photo: True on every item — geotag + timestamp enforced in form.html
# type: "check" = Yes/No/NA   |   "text_with_check" = Yes/No/NA + text confirmation

STAGE_GROUPS = {
    "Groundworks & Structure": [1, 2, 3, 4, 5, 6, 7, 8, 9, 11],
    "Roof": [10, 12, 13, 14],
    "Internal Structure": [15, 16, 17, 18, 19, 20],
    "1st Fix": [21, 22, 23, 24],
    "Plastering & Lining": [25],
    "2nd Fix & Finishes": [26, 27, 28, 29, 30, 31],
    "Finals & Handover": [32, 33, 34, 35, 36, 37],
}

STAGES = {
    1: {
        "number": 1,
        "name": "Foundations",
        "short_name": "01 — Foundations",
        "group": "Groundworks & Structure",
        "applies_to": "Groundworkers",
        "items": [
            {"id": "01_01", "text": "Setting out dimensions checked and correct per drawings", "type": "check", "photo": True},
            {"id": "01_02", "text": "Excavation depth to firm bearing or engineer's specification", "type": "check", "photo": True},
            {"id": "01_03", "text": "Bottom of excavation clean and free from loose material", "type": "check", "photo": True},
            {"id": "01_04", "text": "Concrete mix correct — confirm mix used", "type": "text_with_check", "placeholder": "e.g. C20/25 RC25", "photo": True},
            {"id": "01_05", "text": "Concrete placed in correct temperatures (above 2°C)", "type": "check", "photo": True},
            {"id": "01_06", "text": "Concrete level correct as per drawings", "type": "check", "photo": True},
            {"id": "01_07", "text": "No standing water in excavation prior to pour", "type": "check", "photo": True},
            {"id": "01_08", "text": "Foundation width and depth match engineer's drawings", "type": "check", "photo": True},
        ]
    },
    2: {
        "number": 2,
        "name": "Substructure Brickwork",
        "short_name": "02 — Substructure Brickwork",
        "group": "Groundworks & Structure",
        "applies_to": "Bricklayers",
        "items": [
            {"id": "02_01", "text": "Blockwork fully bedded, all joints full and flush", "type": "check", "photo": True},
            {"id": "02_02", "text": "Blockwork level and plumb, correct height to DPC", "type": "check", "photo": True},
            {"id": "02_03", "text": "DPC installed at correct height, lapped minimum 150mm and sealed", "type": "check", "photo": True},
            {"id": "02_04", "text": "Wall ties correct type, spacing 450mm vert / 750mm horiz. At openings 225mm vert", "type": "check", "photo": True},
            {"id": "02_05", "text": "Cavity clean and free from debris and mortar droppings", "type": "check", "photo": True},
            {"id": "02_06", "text": "Cavity width consistent throughout", "type": "check", "photo": True},
            {"id": "02_07", "text": "Internal walls bonded to cavity walls — wall tie bonding NOT permitted", "type": "check", "photo": True},
            {"id": "02_08", "text": "Insulation installed tightly, no voids, not bridging cavity", "type": "check", "photo": True},
        ]
    },
    3: {
        "number": 3,
        "name": "Drainage",
        "short_name": "03 — Drainage",
        "group": "Groundworks & Structure",
        "applies_to": "Groundworkers",
        "items": [
            {"id": "03_01", "text": "Drainage laid to correct falls — min 1:40 for 100mm pipe", "type": "check", "photo": True},
            {"id": "03_02", "text": "Pipes bedded and surrounded correctly per contract drawings", "type": "check", "photo": True},
            {"id": "03_03", "text": "All joints connected and drainage tested for leaks", "type": "check", "photo": True},
            {"id": "03_04", "text": "Inspection chambers installed at correct locations, aligned correctly", "type": "check", "photo": True},
            {"id": "03_05", "text": "Rodding access points provided at all changes of direction", "type": "check", "photo": True},
            {"id": "03_06", "text": "Drainage pressure tested and signed off", "type": "check", "photo": True},
            {"id": "03_07", "text": "Service entries sealed, insulated and in correct position", "type": "check", "photo": True},
            {"id": "03_08", "text": "All service pipes capped off", "type": "check", "photo": True},
            {"id": "03_09", "text": "Mains water pipe through duct insulated from top of pipe to 1m below ground", "type": "check", "photo": True},
        ]
    },
    4: {
        "number": 4,
        "name": "Ground Floor Slab",
        "short_name": "04 — Ground Floor Slab",
        "group": "Groundworks & Structure",
        "applies_to": "Groundworkers",
        "items": [
            {"id": "04_01", "text": "DPC lapped under floor planks minimum 150mm and sealed", "type": "check", "photo": True},
            {"id": "04_02", "text": "Air bricks installed per drawings, fully bedded and correctly aligned", "type": "check", "photo": True},
            {"id": "04_03", "text": "Ground floor slab level and to correct thickness per drawings", "type": "check", "photo": True},
            {"id": "04_04", "text": "Insulation installed below slab per specification", "type": "check", "photo": True},
            {"id": "04_05", "text": "Thresholds at correct level per PFC standard detail", "type": "check", "photo": True},
            {"id": "04_06", "text": "All service penetrations sealed and insulated", "type": "check", "photo": True},
            {"id": "04_07", "text": "Slab finished to correct tolerance (±3mm under 2m straight edge)", "type": "check", "photo": True},
            {"id": "04_08", "text": "Good grade stone fully compacted, level working platform ready for scaffold", "type": "check", "photo": True},
        ]
    },
    5: {
        "number": 5,
        "name": "Brick Wrap Around",
        "short_name": "05 — Brick Wrap Around",
        "group": "Groundworks & Structure",
        "applies_to": "Bricklayers",
        "items": [
            {"id": "05_01", "text": "Scaffold mats / crash deck in place before brickwork commences", "type": "check", "photo": True},
            {"id": "05_02", "text": "Brickwork level, plumb and true to gauge", "type": "check", "photo": True},
            {"id": "05_03", "text": "Mortar joints full, perpends vertically aligned", "type": "check", "photo": True},
            {"id": "05_04", "text": "Wall ties correct type, spacing 450mm vert / 750mm horiz. At openings 225mm vert. Not falling back into blockwork", "type": "check", "photo": True},
            {"id": "05_05", "text": "PART L 1b — Cavity wall insulation installed tightly with no gaps or voids, not bridging cavity. Full width of cavity filled. Photo must show insulation coverage across full wall section", "type": "check", "photo": True},
            {"id": "05_05b", "text": "PART L 1c — Thermal bridging at window and door reveals: cavity closers correctly installed, insulated reveal liners in place, no uninsulated cold bridges at junctions. Photo must show reveal detail with insulated closer in place", "type": "check", "photo": True},
            {"id": "05_06", "text": "Cavity clean and free from mortar droppings", "type": "check", "photo": True},
            {"id": "05_07", "text": "DPC to top of floor planks and brickwork in accordance with drawings", "type": "check", "photo": True},
            {"id": "05_08", "text": "Weep holes at 450mm centres above all openings, above lintels but not bedded", "type": "check", "photo": True},
            {"id": "05_09", "text": "Reveals — margins even and vertically aligned, all joints full", "type": "check", "photo": True},
            {"id": "05_10", "text": "Lintels fully bedded and level with correct bearings", "type": "check", "photo": True},
            {"id": "05_11", "text": "PVC lintel covers built into all lintels", "type": "check", "photo": True},
            {"id": "05_12", "text": "Pennyfarthing stones built in with DPC protective covering at correct locations", "type": "check", "photo": True},
        ]
    },
    6: {
        "number": 6,
        "name": "Brickwork to First",
        "short_name": "06 — Brickwork to First",
        "group": "Groundworks & Structure",
        "applies_to": "Bricklayers",
        "items": [
            {"id": "06_01", "text": "Brickwork level, plumb and true to gauge at first floor level", "type": "check", "photo": True},
            {"id": "06_02", "text": "Mortar joints full, perpends aligned vertically", "type": "check", "photo": True},
            {"id": "06_03", "text": "Wall ties correctly installed — confirm tie type used", "type": "text_with_check", "placeholder": "e.g. Ancon RT2 stainless steel", "photo": True},
            {"id": "06_04", "text": "Cavity trays installed with min 75mm turn-up at stop ends, free from debris", "type": "check", "photo": True},
            {"id": "06_05", "text": "Stepped trays fully bedded and clean within cavity", "type": "check", "photo": True},
            {"id": "06_06", "text": "Weep holes at 450mm centres above all openings, above lintels not bedded", "type": "check", "photo": True},
            {"id": "06_07", "text": "PART L 2a — Insulation continuity at joist level junction: insulation installed tightly with no gaps at wall/floor interface, full fill maintained across joist hangers and at all structural junctions. Photo must show insulation continuous at the floor/wall junction with no cold bridges", "type": "check", "photo": True},
            {"id": "06_08", "text": "Lintels fully bedded and level, steels with correct bearings", "type": "check", "photo": True},
            {"id": "06_09", "text": "Lateral restraint straps built in correctly on joists and gables per drawings", "type": "check", "photo": True},
            {"id": "06_10", "text": "Storey height correct per drawings, blockwork level under joists", "type": "check", "photo": True},
            {"id": "06_11", "text": "Separating walls to robust details Part E — cavity clean, no mortar bridging", "type": "check", "photo": True},
            {"id": "06_12", "text": "Fire socks installed in accordance with contract drawings", "type": "check", "photo": True},
            {"id": "06_13", "text": "Internal insulated separating walls covered at end of each lift", "type": "check", "photo": True},
            {"id": "06_14", "text": "Expansion joints in correct place per drawings and vertical", "type": "check", "photo": True},
        ]
    },
    7: {
        "number": 7,
        "name": "Joist",
        "short_name": "07 — Joist",
        "group": "Groundworks & Structure",
        "applies_to": "Carpenters",
        "items": [
            {"id": "07_01", "text": "Joists installed strictly in accordance with contract design drawings", "type": "check", "photo": True},
            {"id": "07_02", "text": "All joist hangers fully nailed — all nail holes used", "type": "check", "photo": True},
            {"id": "07_03", "text": "All Z clips fully nailed", "type": "check", "photo": True},
            {"id": "07_04", "text": "Vertical and horizontal straps have minimum 8 fixings", "type": "check", "photo": True},
            {"id": "07_05", "text": "All perimeter noggins installed", "type": "check", "photo": True},
            {"id": "07_06", "text": "Strongbacks fully nailed and flush with blockwork", "type": "check", "photo": True},
            {"id": "07_07", "text": "Joists flush with blockwork — not protruding into cavity", "type": "check", "photo": True},
            {"id": "07_08", "text": "All flooring set in 10–15mm from blockwork", "type": "check", "photo": True},
            {"id": "07_09", "text": "All floor joints fully glued", "type": "check", "photo": True},
            {"id": "07_10", "text": "All tacked nails removed and holes glued", "type": "check", "photo": True},
            {"id": "07_11", "text": "Floor perimeter sealed", "type": "check", "photo": True},
        ]
    },
    8: {
        "number": 8,
        "name": "Brickwork 2nd Lift",
        "short_name": "08 — Brickwork 2nd Lift",
        "group": "Groundworks & Structure",
        "applies_to": "Bricklayers",
        "items": [
            {"id": "08_01", "text": "Brickwork level, plumb and true to gauge", "type": "check", "photo": True},
            {"id": "08_02", "text": "Mortar joints full, perpends aligned vertically", "type": "check", "photo": True},
            {"id": "08_03", "text": "Wall ties correct type and spacing — confirm tie type", "type": "text_with_check", "placeholder": "e.g. Ancon RT2 stainless steel", "photo": True},
            {"id": "08_04", "text": "Cavity trays installed with min 75mm turn-up at stop ends", "type": "check", "photo": True},
            {"id": "08_05", "text": "Weep holes at 450mm centres above all openings", "type": "check", "photo": True},
            {"id": "08_06", "text": "Insulation installed tightly, no voids, not bridging cavity", "type": "check", "photo": True},
            {"id": "08_07", "text": "Lintels fully bedded and level with correct bearings", "type": "check", "photo": True},
            {"id": "08_08", "text": "Lateral restraint straps built in correctly per drawings", "type": "check", "photo": True},
            {"id": "08_09", "text": "Fire socks installed in accordance with contract drawings", "type": "check", "photo": True},
            {"id": "08_10", "text": "PVC lintel covers built into all lintels", "type": "check", "photo": True},
            {"id": "08_11", "text": "Separating walls to robust details Part E — cavity clean, no mortar bridging", "type": "check", "photo": True},
            {"id": "08_12", "text": "Internal insulated separating walls covered at end of each lift", "type": "check", "photo": True},
        ]
    },
    9: {
        "number": 9,
        "name": "Brickwork Top Out & Plate",
        "short_name": "09 — Brickwork Top Out & Plate",
        "group": "Groundworks & Structure",
        "applies_to": "Bricklayers",
        "items": [
            {"id": "09_01", "text": "Top course of brickwork level and true per drawings", "type": "check", "photo": True},
            {"id": "09_02", "text": "Plate halved, fully bedded and nailed at all joints", "type": "check", "photo": True},
            {"id": "09_03", "text": "Plate straps fixed at maximum 150mm centres", "type": "check", "photo": True},
            {"id": "09_04", "text": "All bed joints and perpends fully filled at top out", "type": "check", "photo": True},
            {"id": "09_05", "text": "Correct height to roof plate per drawings", "type": "check", "photo": True},
            {"id": "09_06", "text": "Joists blocked, filled and mastic at party walls", "type": "check", "photo": True},
            {"id": "09_07", "text": "All cavities closed at top with appropriate cavity closer", "type": "check", "photo": True},
            {"id": "09_08", "text": "Temporary protection to top of brickwork if rain expected", "type": "check", "photo": True},
        ]
    },
    10: {
        "number": 10,
        "name": "Trusses",
        "short_name": "10 — Trusses",
        "group": "Roof",
        "applies_to": "Carpenters",
        "items": [
            {"id": "10_01", "text": "No damaged trusses or spandrel panels — all gang nail plates intact", "type": "check", "photo": True},
            {"id": "10_02", "text": "Trusses installed in accordance with contract drawings and engineer's specification", "type": "check", "photo": True},
            {"id": "10_03", "text": "All truss clips fitted including girder truss clips", "type": "check", "photo": True},
            {"id": "10_04", "text": "All clips, shoes and hangers fully nailed — all holes used", "type": "check", "photo": True},
            {"id": "10_05", "text": "All bracing has minimum 2 nails per truss", "type": "check", "photo": True},
            {"id": "10_06", "text": "All bracing installed per manufacturer's instructions", "type": "check", "photo": True},
            {"id": "10_07", "text": "Diagonal bracing fixed to plate or lowest node point on truss", "type": "check", "photo": True},
            {"id": "10_08", "text": "All bracing flush with internal blockwork", "type": "check", "photo": True},
            {"id": "10_09", "text": "All straps have minimum 8 fixings and correctly positioned", "type": "check", "photo": True},
            {"id": "10_10", "text": "All trusses level and plumb", "type": "check", "photo": True},
            {"id": "10_11", "text": "Plate straps fixed per engineer's drawings", "type": "check", "photo": True},
            {"id": "10_12", "text": "Girder trusses nailed together to manufacturer's specification", "type": "check", "photo": True},
            {"id": "10_13", "text": "Valley trusses supported underneath with brace/tilt fillet", "type": "check", "photo": True},
            {"id": "10_14", "text": "Spandrel panels plumb, all joints have intumescent mastic and are over-boarded", "type": "check", "photo": True},
            {"id": "10_15", "text": "Spandrels sat on Rockwool and strapped to party wall", "type": "check", "photo": True},
            {"id": "10_16", "text": "Soffit voids filled with fire sock at party wall junctions", "type": "check", "photo": True},
            {"id": "10_17", "text": "Rockwool fire check at party walls continues into soffit zone", "type": "check", "photo": True},
            {"id": "10_18", "text": "All fascias and soffits straight, fascias double nailed, soffits nailed to cradles", "type": "check", "photo": True},
            {"id": "10_19", "text": "All UPVC installed correctly per drawings", "type": "check", "photo": True},
        ]
    },
    11: {
        "number": 11,
        "name": "Brickwork Gables",
        "short_name": "11 — Brickwork Gables",
        "group": "Groundworks & Structure",
        "applies_to": "Bricklayers",
        "items": [
            {"id": "11_01", "text": "Gable brickwork level, plumb and true to gauge", "type": "check", "photo": True},
            {"id": "11_02", "text": "Mortar joints full, perpends aligned vertically", "type": "check", "photo": True},
            {"id": "11_03", "text": "Gable ladders fixed and propped correctly", "type": "check", "photo": True},
            {"id": "11_04", "text": "Gable properly tied back to roof structure", "type": "check", "photo": True},
            {"id": "11_05", "text": "Cavity closed at gable verge with appropriate cavity closer", "type": "check", "photo": True},
            {"id": "11_06", "text": "Verge detail matches contract drawings", "type": "check", "photo": True},
            {"id": "11_07", "text": "Temporary protection or patination provided to all leadwork", "type": "check", "photo": True},
            {"id": "11_08", "text": "All external brickwork free from dust, mortar, debris", "type": "check", "photo": True},
        ]
    },
    12: {
        "number": 12,
        "name": "Felt & Batten",
        "short_name": "12 — Felt & Batten",
        "group": "Roof",
        "applies_to": "Roof Tilers",
        "items": [
            {"id": "12_01", "text": "Fire separation installed to underside of felt between each batten and to back of fascia", "type": "check", "photo": True},
            {"id": "12_02", "text": "Eaves support trays installed per manufacturer's fixing recommendations", "type": "check", "photo": True},
            {"id": "12_03", "text": "Felt laid straight, 10mm drape continuous between rafters", "type": "check", "photo": True},
            {"id": "12_04", "text": "Horizontal laps minimum 150mm", "type": "check", "photo": True},
            {"id": "12_05", "text": "Vertical laps minimum 100mm, coinciding with a rafter", "type": "check", "photo": True},
            {"id": "12_06", "text": "At valleys — underlay overlaps minimum 300mm at centre line", "type": "check", "photo": True},
            {"id": "12_07", "text": "At hip level — underlay overlaps at hip line by minimum 150mm", "type": "check", "photo": True},
            {"id": "12_08", "text": "At side and top abutments — underlay turned up 50mm on vertical surface", "type": "check", "photo": True},
            {"id": "12_09", "text": "Where dry verges used — underlay overhangs verge per tile manufacturer's spec", "type": "check", "photo": True},
            {"id": "12_10", "text": "For dry ridge — underlay terminates below apex per manufacturer's spec", "type": "check", "photo": True},
            {"id": "12_11", "text": "Battens nailed into each rafter — minimum nail size 65 x 3.35mm", "type": "check", "photo": True},
            {"id": "12_12", "text": "No batten shorter than 1200mm long, fixed parallel with eaves and ridge line", "type": "check", "photo": True},
            {"id": "12_13", "text": "No more than one joint in any four consecutive battens", "type": "check", "photo": True},
            {"id": "12_14", "text": "All batten ends splay nailed and supported at hips and valleys", "type": "check", "photo": True},
            {"id": "12_15", "text": "First batten at eaves set for 45–55mm overhang or centre of gutter", "type": "check", "photo": True},
        ]
    },
    13: {
        "number": 13,
        "name": "Roof Tile",
        "short_name": "13 — Roof Tile",
        "group": "Roof",
        "applies_to": "Roof Tilers",
        "items": [
            {"id": "13_01", "text": "Every tile mechanically fixed", "type": "check", "photo": True},
            {"id": "13_02", "text": "All tiles free from defects, chips or heavy scratches", "type": "check", "photo": True},
            {"id": "13_03", "text": "Gauge and headlap correct per site specification — confirm gauge and headlap", "type": "text_with_check", "placeholder": "e.g. Gauge: 100mm, Headlap: 75mm", "photo": True},
            {"id": "13_04", "text": "Fixing nail type confirmed", "type": "text_with_check", "placeholder": "e.g. Copper / Stainless Steel / Silicon Bronze", "photo": True},
            {"id": "13_05", "text": "Lead flashings, aprons, gutters, valleys and saddles fitted per BLM guide", "type": "check", "photo": True},
            {"id": "13_06", "text": "Ridge tiles bedded or dry-fixed correctly, overlap minimum 75mm", "type": "check", "photo": True},
            {"id": "13_07", "text": "Hip and valley intersections neat, correctly detailed and watertight", "type": "check", "photo": True},
            {"id": "13_08", "text": "Verge detail installed correctly per specification", "type": "check", "photo": True},
            {"id": "13_09", "text": "All penetrations through roof sealed correctly", "type": "check", "photo": True},
            {"id": "13_10", "text": "Roof left clean — no debris or dust on surface or in gutters", "type": "check", "photo": True},
        ]
    },
    14: {
        "number": 14,
        "name": "Gutter",
        "short_name": "14 — Gutter",
        "group": "Roof",
        "applies_to": "Carpenters / Roof Tilers",
        "items": [
            {"id": "14_01", "text": "Gutters installed to correct falls — minimum 1:600", "type": "check", "photo": True},
            {"id": "14_02", "text": "All gutter joints sealed and watertight", "type": "check", "photo": True},
            {"id": "14_03", "text": "All gutter brackets installed at correct centres", "type": "check", "photo": True},
            {"id": "14_04", "text": "Downpipes connected and discharging to correct drainage point", "type": "check", "photo": True},
            {"id": "14_05", "text": "Rainwater goods tested under running water — no leaks", "type": "check", "photo": True},
            {"id": "14_06", "text": "Outlet positions correct per drawings", "type": "check", "photo": True},
            {"id": "14_07", "text": "All fascias and soffits clean and free from damage", "type": "check", "photo": True},
            {"id": "14_08", "text": "All fascia and soffit corner and joint trims installed and fixed", "type": "check", "photo": True},
        ]
    },
    15: {
        "number": 15,
        "name": "Screed Prep",
        "short_name": "15 — Screed Prep",
        "group": "Internal Structure",
        "applies_to": "Groundworkers / Site Manager",
        "items": [
            {"id": "15_01", "text": "Subfloor clean and free from all debris", "type": "check", "photo": True},
            {"id": "15_02", "text": "Any pipework below screed protected and route documented", "type": "check", "photo": True},
            {"id": "15_03", "text": "PART L 2b — Floor insulation boards installed before screed: correct thickness per SAP calculation, all joints tightly butted with no gaps, insulation continuous to perimeter insulation strip with no cold bridge at wall junction. Photo must show insulation fully covering floor with perimeter strip in place", "type": "check", "photo": True},
            {"id": "15_04", "text": "Perimeter insulation strip installed around all walls — correct height to match screed + floor finish depth", "type": "check", "photo": True},
            {"id": "15_05", "text": "Expansion joints marked where required per design", "type": "check", "photo": True},
            {"id": "15_06", "text": "Substrate inspected for cracks or defects — none present", "type": "check", "photo": True},
            {"id": "15_07", "text": "Damp proof membrane lapped minimum 150mm and sealed", "type": "check", "photo": True},
            {"id": "15_08", "text": "All service routes confirmed and marked before screed", "type": "check", "photo": True},
            {"id": "15_09", "text": "Level datum points set at correct finished floor level", "type": "check", "photo": True},
        ]
    },
    16: {
        "number": 16,
        "name": "Underfloor Heating",
        "short_name": "16 — Underfloor Heating",
        "group": "Internal Structure",
        "applies_to": "Plumbers",
        "items": [
            {"id": "16_01", "text": "UFH pipes installed per manufacturer's layout drawings", "type": "check", "photo": True},
            {"id": "16_02", "text": "Pipe spacing correct per specification", "type": "check", "photo": True},
            {"id": "16_03", "text": "All loops pressure tested at 6 bar and held for minimum 1 hour", "type": "check", "photo": True},
            {"id": "16_04", "text": "Pressure gauge reading photographed — no leaks on any loop", "type": "check", "photo": True},
            {"id": "16_05", "text": "All manifold valves open and labelled correctly", "type": "check", "photo": True},
            {"id": "16_06", "text": "Actuator heads match thermostats", "type": "check", "photo": True},
            {"id": "16_07", "text": "Flow and return clearly identified", "type": "check", "photo": True},
            {"id": "16_08", "text": "Manifold fixed securely to wall at correct height", "type": "check", "photo": True},
            {"id": "16_09", "text": "Pipe routes fully documented and photographed before screed cover", "type": "check", "photo": True},
        ]
    },
    17: {
        "number": 17,
        "name": "Screed",
        "short_name": "17 — Screed",
        "group": "Internal Structure",
        "applies_to": "Groundworkers / Screed Contractor",
        "items": [
            {"id": "17_01", "text": "Screed mix correct per specification — confirm mix", "type": "text_with_check", "placeholder": "e.g. 1:4.5 sand cement or liquid screed", "photo": True},
            {"id": "17_02", "text": "Screed thickness correct per design — minimum 65mm on UFH", "type": "check", "photo": True},
            {"id": "17_03", "text": "PART L 1a — Floor insulation continuity under screed: perimeter insulation strip continuous and unbroken at all wall junctions, insulation not displaced during pour, screed does not bridge insulation at perimeter. Photo must show perimeter edge detail with strip intact and screed poured tight to it", "type": "check", "photo": True},
            {"id": "17_04", "text": "Screed level to tolerance (±3mm under 2m straight edge)", "type": "check", "photo": True},
            {"id": "17_05", "text": "Perimeter insulation strip intact and at correct height throughout", "type": "check", "photo": True},
            {"id": "17_06", "text": "Screed joints formed at doorways between rooms", "type": "check", "photo": True},
            {"id": "17_07", "text": "Screed protected from traffic for minimum 24 hours after pour", "type": "check", "photo": True},
            {"id": "17_08", "text": "No cracking or delamination visible on inspection", "type": "check", "photo": True},
            {"id": "17_09", "text": "Sound coat applied correctly where required", "type": "check", "photo": True},
        ]
    },
    18: {
        "number": 18,
        "name": "Stairs",
        "short_name": "18 — Stairs",
        "group": "Internal Structure",
        "applies_to": "Carpenters",
        "items": [
            {"id": "18_01", "text": "Stairs installed in accordance with structural drawings", "type": "check", "photo": True},
            {"id": "18_02", "text": "All fixings adequate and secure", "type": "check", "photo": True},
            {"id": "18_03", "text": "Treads do not squeak or deflect excessively", "type": "check", "photo": True},
            {"id": "18_04", "text": "Even margins on strings both sides", "type": "check", "photo": True},
            {"id": "18_05", "text": "Handrail height correct — minimum 900mm from nosing", "type": "check", "photo": True},
            {"id": "18_06", "text": "Balustrade spindle spacing max 100mm", "type": "check", "photo": True},
            {"id": "18_07", "text": "Newel posts secure and plumb", "type": "check", "photo": True},
            {"id": "18_08", "text": "All stair dimensions within Building Regulations tolerances", "type": "check", "photo": True},
            {"id": "18_09", "text": "Stair treads protected after installation", "type": "check", "photo": True},
        ]
    },
    19: {
        "number": 19,
        "name": "Windows",
        "short_name": "19 — Windows",
        "group": "Internal Structure",
        "applies_to": "Window Installer",
        "items": [
            {"id": "19_01", "text": "Windows installed plumb, level and square", "type": "check", "photo": True},
            {"id": "19_02", "text": "All fixings per manufacturer's requirements", "type": "check", "photo": True},
            {"id": "19_03", "text": "Sills and cills bedded correctly with no gaps", "type": "check", "photo": True},
            {"id": "19_04", "text": "Cavity closers installed around all frames", "type": "check", "photo": True},
            {"id": "19_05", "text": "DPCs installed at cills and jambs correctly", "type": "check", "photo": True},
            {"id": "19_06", "text": "Trickle ventilators installed where required by spec", "type": "check", "photo": True},
            {"id": "19_07", "text": "All opening lights operate correctly — no binding or rattling", "type": "check", "photo": True},
            {"id": "19_08", "text": "Thermal breaks intact — no cold bridging", "type": "check", "photo": True},
            {"id": "19_09", "text": "Mastic seal to external perimeter complete and neat", "type": "check", "photo": True},
            {"id": "19_10", "text": "Windows below 800mm floor level have compliant guarding", "type": "check", "photo": True},
        ]
    },
    20: {
        "number": 20,
        "name": "Top Tack & Metal Stud",
        "short_name": "20 — Top Tack & Metal Stud",
        "group": "Internal Structure",
        "applies_to": "Carpenters / Drylining",
        "items": [
            {"id": "20_01", "text": "All partitions installed per contract drawings", "type": "check", "photo": True},
            {"id": "20_02", "text": "Metal stud plumb, level and true — max 600mm centres", "type": "check", "photo": True},
            {"id": "20_03", "text": "Head and sole plates fixed correctly to structure", "type": "check", "photo": True},
            {"id": "20_04", "text": "Timber sole plate installed to all metal stud partitions", "type": "check", "photo": True},
            {"id": "20_05", "text": "All service routes accommodated within partitions", "type": "check", "photo": True},
            {"id": "20_06", "text": "All pattress plates installed for all wall fixtures throughout property", "type": "check", "photo": True},
            {"id": "20_07", "text": "Separating wall acoustic details maintained throughout", "type": "check", "photo": True},
            {"id": "20_08", "text": "Fire stopping installed at all partition heads", "type": "check", "photo": True},
            {"id": "20_09", "text": "2m rule clearance from stairs to bulkhead", "type": "check", "photo": True},
            {"id": "20_10", "text": "PART L 3b — Thermal bridging at all wall/ceiling/floor junctions: insulated cavity closers fitted at all openings, insulation continuous at all structural junctions with no uninsulated gaps. Photo must show insulation continuity at junctions with no cold bridges", "type": "check", "photo": True},
            {"id": "20_11", "text": "SHOWER — Studwork uprights at maximum 200mm centres. Photo must show tape measure confirming 200mm centres across full stud bay", "type": "check", "photo": True},
            {"id": "20_12", "text": "SHOWER — Studwork uprights fixed to both head plate and sole plate with correct fixings. Photo must show fixing at head and sole plate", "type": "check", "photo": True},
            {"id": "20_13", "text": "SHOWER — Two layers of 15mm moisture-resistant board fixed at 200mm centres with staggered joints. Each layer has minimum 50mm overhang beyond shower tray on each side. Photo must show both layers in place with overhang clearly visible over tray line", "type": "check", "photo": True},
        ]
    },
    21: {
        "number": 21,
        "name": "Plumber 1st Fix",
        "short_name": "21 — Plumber 1st Fix",
        "group": "1st Fix",
        "applies_to": "Plumbers",
        "items": [
            {"id": "21_01", "text": "All pipework installed per drawings — hot and cold pipes identified with colour tape (red/blue)", "type": "check", "photo": True},
            {"id": "21_02", "text": "All internal pipework pressure tested — confirm test pressure", "type": "text_with_check", "placeholder": "e.g. 1.5x working pressure for 1 hour", "photo": True},
            {"id": "21_03", "text": "Pressure test witnessed, monitored daily and signed off by plumber", "type": "check", "photo": True},
            {"id": "21_04", "text": "Gas supply pipework fitted correctly, not fouling kitchen units", "type": "check", "photo": True},
            {"id": "21_05", "text": "All pipes clipped at correct centres", "type": "check", "photo": True},
            {"id": "21_06", "text": "SVPs adequately fixed with plugs and screws", "type": "check", "photo": True},
            {"id": "21_07", "text": "UFH manifold connected, all valves open, no leaks", "type": "check", "photo": True},
            {"id": "21_08", "text": "Shower trays installed per specification", "type": "check", "photo": True},
            {"id": "21_09", "text": "Waste under shower tray sealed and tested — no leaks", "type": "check", "photo": True},
            {"id": "21_10", "text": "Hair felt fitted to copper pipes where expansion noise risk", "type": "check", "photo": True},
            {"id": "21_11", "text": "Soils tested and confirmed watertight", "type": "check", "photo": True},
            {"id": "21_12", "text": "All service penetrations through structure sealed", "type": "check", "photo": True},
            {"id": "21_13", "text": "Plastic pipework on blockwork walls has metal tape applied", "type": "check", "photo": True},
            {"id": "21_14", "text": "WC cold fill installed and capped", "type": "check", "photo": True},
            {"id": "21_15", "text": "SHOWER — Sand and cement bed under shower tray: full bed laid across entire tray footprint, correct depth, tray pressed firmly into bed. Photo must show the full bed covering the complete tray area before tray is seated", "type": "check", "photo": True},
        ]
    },
    22: {
        "number": 22,
        "name": "Electrical 1st Fix",
        "short_name": "22 — Electrical 1st Fix",
        "group": "1st Fix",
        "applies_to": "Electricians",
        "items": [
            {"id": "22_01", "text": "All cables run vertically and horizontally — not diagonally", "type": "check", "photo": True},
            {"id": "22_02", "text": "All electrical fittings installed per house type electrical plan", "type": "check", "photo": True},
            {"id": "22_03", "text": "All back boxes securely fixed, in line and level — metal back boxes used", "type": "check", "photo": True},
            {"id": "22_04", "text": "Grommets fitted to all metal back boxes", "type": "check", "photo": True},
            {"id": "22_05", "text": "All cables to consumer unit labelled and taped", "type": "check", "photo": True},
            {"id": "22_06", "text": "No smoke or heat detectors within 300mm of window, door or trap hatch", "type": "check", "photo": True},
            {"id": "22_07", "text": "All containment and capping complete", "type": "check", "photo": True},
            {"id": "22_08", "text": "All ducting foil taped and sealed at all penetrations", "type": "check", "photo": True},
            {"id": "22_09", "text": "Sub-main cable installed and glanded into position", "type": "check", "photo": True},
            {"id": "22_10", "text": "All BT, TV and data cables installed", "type": "check", "photo": True},
            {"id": "22_11", "text": "Metal fixings in place in ceilings for light fittings", "type": "check", "photo": True},
            {"id": "22_12", "text": "Cable routes documented and photographed before boarding", "type": "check", "photo": True},
        ]
    },
    23: {
        "number": 23,
        "name": "Carpenter 1st Fix",
        "short_name": "23 — Carpenter 1st Fix",
        "group": "1st Fix",
        "applies_to": "Carpenters",
        "items": [
            {"id": "23_01", "text": "All stairwell studwork CLS timber and installed per drawings", "type": "check", "photo": True},
            {"id": "23_02", "text": "Window boards level and square, correct return length per spec", "type": "check", "photo": True},
            {"id": "23_03", "text": "Window board wings correct length and sanded", "type": "check", "photo": True},
            {"id": "23_04", "text": "All pattresses in place and fixed securely", "type": "check", "photo": True},
            {"id": "23_05", "text": "All door linings fixed with 8 screws per side — plumb, level and square", "type": "check", "photo": True},
            {"id": "23_06", "text": "Stair treads do not squeak, even margins on string both sides", "type": "check", "photo": True},
            {"id": "23_07", "text": "Stair treads protected after installation", "type": "check", "photo": True},
            {"id": "23_08", "text": "Handrails and newel posts in place where required", "type": "check", "photo": True},
        ]
    },
    24: {
        "number": 24,
        "name": "Pre-Plaster Inspection",
        "short_name": "24 — Pre-Plaster Inspection",
        "group": "1st Fix",
        "applies_to": "Site Manager",
        "items": [
            {"id": "24_01", "text": "All 1st fix trades signed off and complete", "type": "check", "photo": True},
            {"id": "24_02", "text": "10mm perimeter gap maintained to floor throughout entire plot", "type": "check", "photo": True},
            {"id": "24_03", "text": "Party wall parge coat applied correctly and fully covering", "type": "check", "photo": True},
            {"id": "24_04", "text": "All blockwork joints full — no holes, gaps or missing blocks", "type": "check", "photo": True},
            {"id": "24_05", "text": "No holes in roofing sarking felt — all penetrations through roof sealed", "type": "check", "photo": True},
            {"id": "24_06", "text": "All penetrations through blockwork sealed", "type": "check", "photo": True},
            {"id": "24_07", "text": "All pattress plates installed for all wall fixtures throughout property", "type": "check", "photo": True},
            {"id": "24_08", "text": "All stud walls to line and level, fixed per manufacturer's recommendations", "type": "check", "photo": True},
            {"id": "24_09", "text": "Timber base plate to all metal studwork installed", "type": "check", "photo": True},
            {"id": "24_10", "text": "2m headroom clearance from stairs to bulkhead confirmed", "type": "check", "photo": True},
            {"id": "24_11", "text": "Plot fully cleaned out and protection applied to all surfaces", "type": "check", "photo": True},
            {"id": "24_12", "text": "PART L 4a — Air tightness: all service penetrations through the air barrier (floors, walls, ceiling) sealed with appropriate air tightness tape or mastic. Photo must show sealed penetrations at each service entry through the fabric", "type": "check", "photo": True},
            {"id": "24_13", "text": "PART L 4b — Air tightness at junctions: all wall/floor/ceiling junctions taped and sealed, loft hatch sealed with draught seal, all electrical back boxes fitted with air tightness membranes where required. Photo must show junction sealing detail", "type": "check", "photo": True},
            {"id": "24_14", "text": "PART L 5 — Party wall airtightness: parge coat fully continuous on party wall with no gaps, cracks or missing sections. All service penetrations through party wall sealed. Photo must show completed parge coat across full party wall height", "type": "check", "photo": True},
        ]
    },
    25: {
        "number": 25,
        "name": "Drylining",
        "short_name": "25 — Drylining",
        "group": "Plastering & Lining",
        "applies_to": "Plasterers / Drylining",
        "items": [
            {"id": "25_01", "text": "Plasterboard type correct — moisture resistant and fireline where required", "type": "check", "photo": True},
            {"id": "25_01b", "text": "PART L 3a — Wall insulation continuity: insulation installed behind drylining fully continuous with no gaps, voids or compression, correctly overlapping floor and ceiling insulation layers. Photo must show insulation fully covering wall face with no gaps before boarding", "type": "check", "photo": True},
            {"id": "25_02", "text": "All boards installed per contract drawings, fixings per manufacturer's recommendations", "type": "check", "photo": True},
            {"id": "25_03", "text": "Fixings at correct centres — maximum 300mm", "type": "check", "photo": True},
            {"id": "25_04", "text": "Staggered joints above doors and at ceiling junctions", "type": "check", "photo": True},
            {"id": "25_05", "text": "Staggered screws to prevent board crimping and splitting", "type": "check", "photo": True},
            {"id": "25_06", "text": "Sound insulation installed with no voids", "type": "check", "photo": True},
            {"id": "25_07", "text": "Loft insulation in place to correct specification", "type": "check", "photo": True},
            {"id": "25_08", "text": "All joints taped and filled correctly", "type": "check", "photo": True},
            {"id": "25_09", "text": "All skim coats smooth, uniform and without undulations", "type": "check", "photo": True},
            {"id": "25_10", "text": "All electric boxes clean — perimeter cut out without excess plaster", "type": "check", "photo": True},
            {"id": "25_11", "text": "All windows clean and free from plaster staining", "type": "check", "photo": True},
            {"id": "25_12", "text": "Drylining installed to line and level", "type": "check", "photo": True},
            {"id": "25_13", "text": "All frames and surfaces washed down and areas cleared", "type": "check", "photo": True},
        ]
    },
    26: {
        "number": 26,
        "name": "Kitchen",
        "short_name": "26 — Kitchen",
        "group": "2nd Fix & Finishes",
        "applies_to": "Kitchen Fitter",
        "items": [
            {"id": "26_01", "text": "All kitchen units installed level and plumb", "type": "check", "photo": True},
            {"id": "26_02", "text": "All units fixed per manufacturer's recommendations", "type": "check", "photo": True},
            {"id": "26_03", "text": "Worktops level, all joints tight and sealed", "type": "check", "photo": True},
            {"id": "26_04", "text": "All appliances connected and operational", "type": "check", "photo": True},
            {"id": "26_05", "text": "Extract installed and ducted correctly to outside", "type": "check", "photo": True},
            {"id": "26_06", "text": "All plumbing connections tight with no leaks — test run", "type": "check", "photo": True},
            {"id": "26_07", "text": "Gas connection made by Gas Safe registered engineer — confirm reg number", "type": "text_with_check", "placeholder": "e.g. Gas Safe Reg No: 123456", "photo": True},
            {"id": "26_08", "text": "All electrical connections safe and operational", "type": "check", "photo": True},
            {"id": "26_09", "text": "Grid switch and appliance sockets installed and operational", "type": "check", "photo": True},
            {"id": "26_10", "text": "Upstands and splashback installed, all joints sealed", "type": "check", "photo": True},
        ]
    },
    27: {
        "number": 27,
        "name": "Ceramic Tiler",
        "short_name": "27 — Ceramic Tiler",
        "group": "2nd Fix & Finishes",
        "applies_to": "Ceramic Tilers",
        "items": [
            # Tanking — shower areas
            {"id": "27_01", "text": "SHOWER — Tanking to shower enclosure: tanking membrane applied minimum 50mm past the shower tray line on all sides. Photo must show the 50mm overhang beyond tray edge clearly marked or measured", "type": "check", "photo": True},
            {"id": "27_02", "text": "SHOWER — Tanking tape applied to shower tray perimeter: tape lipped onto tray lip and up onto wall board with correct lapping. Photo must show tape lipped over tray edge with no lifting or gaps", "type": "check", "photo": True},
            {"id": "27_03", "text": "SHOWER — Tanking applied to surround all water feed penetrations: tanking membrane covers minimum 50mm around each pipe entry point. Photo must show each water feed penetration fully tanked", "type": "check", "photo": True},
            {"id": "27_04", "text": "SHOWER — Two coats of tanking paint applied switching horizontal then vertical application to ensure full coverage. Photo must show completed second coat with no missed areas", "type": "check", "photo": True},
            # Ceramic tiles
            {"id": "27_05", "text": "Adhesive applied to walls and back-buttered to tiles (buttered method)", "type": "check", "photo": True},
            {"id": "27_06", "text": "Tiles completed and left minimum 24 hours before grouting", "type": "check", "photo": True},
            {"id": "27_07", "text": "Grouting applied and left minimum 24 hours before silicone", "type": "check", "photo": True},
            {"id": "27_08", "text": "Floor grout colour as specified — confirm colour", "type": "text_with_check", "placeholder": "e.g. Mapei Keracolor S Grey", "photo": True},
            {"id": "27_09", "text": "Wall grout colour as specified — confirm colour", "type": "text_with_check", "placeholder": "e.g. Mapei Keracolor S White", "photo": True},
            {"id": "27_10", "text": "Trim colour as specified — confirm colour", "type": "text_with_check", "placeholder": "e.g. Chrome / Matt Black / White", "photo": True},
            {"id": "27_11", "text": "Tile joints straight and aligned, consistent spacing 3–5mm", "type": "check", "photo": True},
            {"id": "27_12", "text": "No visible cut edges to trims, full length trims used", "type": "check", "photo": True},
            {"id": "27_13", "text": "Anti-crack matting installed under all floor tiles", "type": "check", "photo": True},
            {"id": "27_14", "text": "Floor tiles at correct locations per drawings", "type": "check", "photo": True},
            {"id": "27_15", "text": "Wall tiling to correct locations and heights", "type": "check", "photo": True},
            {"id": "27_16", "text": "Tile colour consistent — one batch used throughout", "type": "check", "photo": True},
            {"id": "27_17", "text": "Spare tiles left for customer repairs", "type": "check", "photo": True},
            {"id": "27_18", "text": "Completed shower enclosure photographed in full", "type": "check", "photo": True},
        ]
    },
    28: {
        "number": 28,
        "name": "Carpenter 2nd Fix",
        "short_name": "28 — Carpenter 2nd Fix",
        "group": "2nd Fix & Finishes",
        "applies_to": "Carpenters",
        "items": [
            {"id": "28_01", "text": "All skirting scribed, mitred and primed — gaps max 1mm", "type": "check", "photo": True},
            {"id": "28_02", "text": "All architrave mitred and primed — gaps max 1mm", "type": "check", "photo": True},
            {"id": "28_03", "text": "Door margins max 2mm — double doors fully align", "type": "check", "photo": True},
            {"id": "28_04", "text": "Hinge cut-outs correct, all screws fitted, primed behind hinges", "type": "check", "photo": True},
            {"id": "28_05", "text": "Door furniture fitted, aligned and latched correctly", "type": "check", "photo": True},
            {"id": "28_06", "text": "All stair spindles and caps fitted — margins max 1mm", "type": "check", "photo": True},
            {"id": "28_07", "text": "All holes around pipes filled and made good", "type": "check", "photo": True},
            {"id": "28_08", "text": "Dowels cut off and sanded", "type": "check", "photo": True},
            {"id": "28_09", "text": "Plot cleaned and all doors protected", "type": "check", "photo": True},
        ]
    },
    29: {
        "number": 29,
        "name": "Plumber 2nd Fix",
        "short_name": "29 — Plumber 2nd Fix",
        "group": "2nd Fix & Finishes",
        "applies_to": "Plumbers",
        "items": [
            {"id": "29_01", "text": "Boiler installed — hot and cold connections correct, no gas or water leaks", "type": "check", "photo": True},
            {"id": "29_01b", "text": "PART L 6a — Hot water cylinder and pipework insulation: cylinder insulated to manufacturer's specification, all hot water pipes insulated for minimum 1m from cylinder and throughout accessible areas. Photo must show cylinder insulation and first metre of pipe insulation", "type": "check", "photo": True},
            {"id": "29_02", "text": "Boiler benchmark book completed and label on boiler showing installer details", "type": "check", "photo": True},
            {"id": "29_03", "text": "Boiler flue fitted correctly with adequate brackets in roof space", "type": "check", "photo": True},
            {"id": "29_04", "text": "Boiler flow and returns correctly fitted", "type": "check", "photo": True},
            {"id": "29_05", "text": "Heating manifold open with no leaks — bypass valve set correctly", "type": "check", "photo": True},
            {"id": "29_06", "text": "All radiators level — TRVs operational, flow and return not crossed", "type": "check", "photo": True},
            {"id": "29_07", "text": "Vent rad flow, return and TRV operational", "type": "check", "photo": True},
            {"id": "29_08", "text": "Cylinder checked for leaks, blow down checked, benchmark completed", "type": "check", "photo": True},
            {"id": "29_09", "text": "Blending valve fitted correctly", "type": "check", "photo": True},
            {"id": "29_10", "text": "Shower screen aligned and secure, tray fully siliconed", "type": "check", "photo": True},
            {"id": "29_11", "text": "All waste pipes and traps tested — no leaks", "type": "check", "photo": True},
            {"id": "29_12", "text": "Washing machine cycle run — no leaks", "type": "check", "photo": True},
            {"id": "29_13", "text": "Cistern level and operational", "type": "check", "photo": True},
            {"id": "29_14", "text": "Toilet pan fixed to wall and floor", "type": "check", "photo": True},
            {"id": "29_15", "text": "Basin and shower hot/cold feeds correctly connected", "type": "check", "photo": True},
            {"id": "29_16", "text": "Bath overflow installed correctly — no leaks", "type": "check", "photo": True},
            {"id": "29_17", "text": "Roof space vents connected and durgos operational", "type": "check", "photo": True},
            {"id": "29_18", "text": "Utility sink overflow connection correct — no leaks", "type": "check", "photo": True},
            {"id": "29_19", "text": "Expansion pipes have cage and correctly installed", "type": "check", "photo": True},
        ]
    },
    30: {
        "number": 30,
        "name": "Electrical 2nd Fix",
        "short_name": "30 — Electrical 2nd Fix",
        "group": "2nd Fix & Finishes",
        "applies_to": "Electricians",
        "items": [
            {"id": "30_01", "text": "All sockets and switches level, tight and scratch-free", "type": "check", "photo": True},
            {"id": "30_02", "text": "All light fittings and downlights installed with lamps", "type": "check", "photo": True},
            {"id": "30_03", "text": "All pendants screwed up and secure", "type": "check", "photo": True},
            {"id": "30_04", "text": "Kitchen grid switch and appliance sockets complete", "type": "check", "photo": True},
            {"id": "30_05", "text": "Earth bonding complete", "type": "check", "photo": True},
            {"id": "30_06", "text": "Heating system fitted and completed", "type": "check", "photo": True},
            {"id": "30_07", "text": "Consumer unit complete, labelled and all blank plates fitted", "type": "check", "photo": True},
            {"id": "30_08", "text": "Surge protection device fitted", "type": "check", "photo": True},
            {"id": "30_09", "text": "All smoke and heat detectors installed, linked and minimum 300mm from any opening", "type": "check", "photo": True},
            {"id": "30_10", "text": "Carbon monoxide detectors installed where required", "type": "check", "photo": True},
        ]
    },
    31: {
        "number": 31,
        "name": "Decorator",
        "short_name": "31 — Decorator",
        "group": "2nd Fix & Finishes",
        "applies_to": "Decorator",
        "items": [
            {"id": "31_01", "text": "All surfaces prepared correctly before painting", "type": "check", "photo": True},
            {"id": "31_02", "text": "Mist coat applied to all new plaster before finish coats", "type": "check", "photo": True},
            {"id": "31_03", "text": "Correct number of finish coats applied per specification", "type": "check", "photo": True},
            {"id": "31_04", "text": "Finish smooth, even and without drips, runs or brush marks", "type": "check", "photo": True},
            {"id": "31_05", "text": "All woodwork primed, undercoated and top coated correctly", "type": "check", "photo": True},
            {"id": "31_06", "text": "Gloss finish on woodwork smooth and even without brush marks", "type": "check", "photo": True},
            {"id": "31_07", "text": "Paint not applied to expansion joints", "type": "check", "photo": True},
            {"id": "31_08", "text": "No paint on windows, ironmongery or fittings", "type": "check", "photo": True},
            {"id": "31_09", "text": "All areas cleaned down after completion", "type": "check", "photo": True},
            {"id": "31_10", "text": "Colour schedule confirmed and correct — confirm colours used", "type": "text_with_check", "placeholder": "e.g. Walls: Dulux Pure Brilliant White, Woodwork: Brilliant White Gloss", "photo": True},
        ]
    },
    32: {
        "number": 32,
        "name": "Plumb Finals",
        "short_name": "32 — Plumb Finals",
        "group": "Finals & Handover",
        "applies_to": "Plumbers",
        "items": [
            {"id": "32_01", "text": "All pipework systems flushed and filled — no air locks", "type": "check", "photo": True},
            {"id": "32_02", "text": "System pressure correct and maintained", "type": "check", "photo": True},
            {"id": "32_03", "text": "All radiators balanced and operational", "type": "check", "photo": True},
            {"id": "32_04", "text": "Underfloor heating commissioned and operational", "type": "check", "photo": True},
            {"id": "32_05", "text": "Boiler commissioned per manufacturer's instructions", "type": "check", "photo": True},
            {"id": "32_06", "text": "Gas installation inspected by Gas Safe registered engineer", "type": "check", "photo": True},
            {"id": "32_07", "text": "Gas tightness test passed and documented", "type": "check", "photo": True},
            {"id": "32_08", "text": "All airing cupboard pipework labelled correctly", "type": "check", "photo": True},
            {"id": "32_09", "text": "Stop cocks labelled correctly", "type": "check", "photo": True},
            {"id": "32_10", "text": "All documentation, warranties and benchmark books left with property", "type": "check", "photo": True},
            {"id": "32_11", "text": "PART L 6b — Heating controls installed and commissioned: programmer/timer, room thermostat and TRVs all operational and correctly set. Hot water thermostat set to 60°C. Photo must show controls display and thermostat settings", "type": "check", "photo": True},
            {"id": "32_12", "text": "PART L 6c — Boiler efficiency and controls: boiler set to weather compensation or load compensation where fitted, flow temperature set correctly per SAP. Confirm boiler flow temperature setting", "type": "text_with_check", "placeholder": "e.g. Flow temp set to 55°C with weather comp enabled", "photo": True},
        ]
    },
    33: {
        "number": 33,
        "name": "Electrical Final",
        "short_name": "33 — Electrical Final",
        "group": "Finals & Handover",
        "applies_to": "Electricians",
        "items": [
            {"id": "33_01", "text": "Full electrical installation test completed", "type": "check", "photo": True},
            {"id": "33_02", "text": "Electrical certificate (EICR) issued and signed — confirm certificate number", "type": "text_with_check", "placeholder": "e.g. EICR Cert No: 12345", "photo": True},
            {"id": "33_03", "text": "Consumer unit labelled correctly, all circuits identified", "type": "check", "photo": True},
            {"id": "33_04", "text": "'Next Inspection' sticker applied to consumer unit", "type": "check", "photo": True},
            {"id": "33_05", "text": "All blank plates fitted to consumer unit", "type": "check", "photo": True},
            {"id": "33_06", "text": "All circuits tested and fully operational", "type": "check", "photo": True},
            {"id": "33_07", "text": "RCD protection confirmed on all circuits", "type": "check", "photo": True},
            {"id": "33_08", "text": "Surge protection device operational", "type": "check", "photo": True},
            {"id": "33_09", "text": "All smoke and heat detectors tested and linked — operational", "type": "check", "photo": True},
            {"id": "33_10", "text": "Carbon monoxide detectors tested and operational", "type": "check", "photo": True},
            {"id": "33_11", "text": "All lights fully operational throughout property", "type": "check", "photo": True},
            {"id": "33_12", "text": "All documentation left with property", "type": "check", "photo": True},
            {"id": "33_13", "text": "PART L 6c — Lighting efficacy: minimum 75% of fixed light fittings are low energy (LED or equivalent, minimum 45 lumens/watt). Confirm number of LED fittings vs total fittings", "type": "text_with_check", "placeholder": "e.g. 18 of 22 fittings LED — 82%", "photo": True},
        ]
    },
    34: {
        "number": 34,
        "name": "Carpenter Final",
        "short_name": "34 — Carpenter Final",
        "group": "Finals & Handover",
        "applies_to": "Carpenters",
        "items": [
            {"id": "34_01", "text": "All ironmongery operational and correctly adjusted", "type": "check", "photo": True},
            {"id": "34_02", "text": "All doors close and are fully aligned — no rattling", "type": "check", "photo": True},
            {"id": "34_03", "text": "All drawers and cupboards operational and adjusted", "type": "check", "photo": True},
            {"id": "34_04", "text": "All shelving and storage installed per specification", "type": "check", "photo": True},
            {"id": "34_05", "text": "Spindle spacing confirmed — does not exceed 100mm", "type": "check", "photo": True},
            {"id": "34_06", "text": "All snag items from pre-handover inspection addressed", "type": "check", "photo": True},
            {"id": "34_07", "text": "All joinery surfaces undamaged and clean", "type": "check", "photo": True},
            {"id": "34_08", "text": "Fire egress windows operational — confirm locations", "type": "check", "photo": True},
        ]
    },
    35: {
        "number": 35,
        "name": "Mastic",
        "short_name": "35 — Mastic",
        "group": "Finals & Handover",
        "applies_to": "Mastic Contractor",
        "items": [
            {"id": "35_01", "text": "All internal mastic lines complete, neat and correct profile (concave)", "type": "check", "photo": True},
            {"id": "35_02", "text": "All external mastic lines complete and weathertight", "type": "check", "photo": True},
            {"id": "35_03", "text": "Correct mastic type and colour used throughout — confirm", "type": "text_with_check", "placeholder": "e.g. Mapesil 100 internal / Soudal Fix All external", "photo": True},
            {"id": "35_04", "text": "No gaps or voids in any mastic lines", "type": "check", "photo": True},
            {"id": "35_05", "text": "Mastic around all sanitaryware complete and neat", "type": "check", "photo": True},
            {"id": "35_06", "text": "Window and door mastic to external perimeter complete", "type": "check", "photo": True},
            {"id": "35_07", "text": "Movement and expansion joints mastics complete", "type": "check", "photo": True},
            {"id": "35_08", "text": "All wet areas internal mastic complete — shower, bath, basin", "type": "check", "photo": True},
            {"id": "35_09", "text": "SHOWER — Mastic applied to full shower tray perimeter prior to shower screen installation: continuous bead with no gaps, correct profile, correct colour. Photo must show completed mastic bead around full tray perimeter before screen is fitted", "type": "check", "photo": True},
        ]
    },
    36: {
        "number": 36,
        "name": "Wardrobe",
        "short_name": "36 — Wardrobe",
        "group": "Finals & Handover",
        "applies_to": "Carpenters / Wardrobe Installer",
        "items": [
            {"id": "36_01", "text": "Wardrobes installed level, plumb and square", "type": "check", "photo": True},
            {"id": "36_02", "text": "All fixings per manufacturer's recommendations", "type": "check", "photo": True},
            {"id": "36_03", "text": "Doors aligned and operating correctly — no binding", "type": "check", "photo": True},
            {"id": "36_04", "text": "Interior fittings installed per customer specification", "type": "check", "photo": True},
            {"id": "36_05", "text": "All surfaces undamaged and clean", "type": "check", "photo": True},
            {"id": "36_06", "text": "All handles and ironmongery fitted correctly", "type": "check", "photo": True},
        ]
    },
    37: {
        "number": 37,
        "name": "Flooring",
        "short_name": "37 — Flooring",
        "group": "Finals & Handover",
        "applies_to": "Flooring Contractor",
        "items": [
            {"id": "37_01", "text": "Subfloor clean, level and dry — moisture reading recorded", "type": "text_with_check", "placeholder": "e.g. Moisture reading: 3% — pass", "photo": True},
            {"id": "37_02", "text": "Underlay installed correctly and fully covers floor area", "type": "check", "photo": True},
            {"id": "37_03", "text": "Floor covering type and colour correct per schedule — confirm", "type": "text_with_check", "placeholder": "e.g. Karndean Van Gogh Washed Scandi Pine", "photo": True},
            {"id": "37_04", "text": "All joints and seams neat, tight and correctly positioned", "type": "check", "photo": True},
            {"id": "37_05", "text": "Threshold strips installed at all doorways", "type": "check", "photo": True},
            {"id": "37_06", "text": "Floor covering correctly fixed or adhered per manufacturer's method", "type": "check", "photo": True},
            {"id": "37_07", "text": "No squeaks, movement or hollow spots", "type": "check", "photo": True},
            {"id": "37_08", "text": "Skirting rebated or beading fitted where required", "type": "check", "photo": True},
            {"id": "37_09", "text": "All areas clean and protected after installation", "type": "check", "photo": True},
        ]
    },
}


def get_stage(number: int) -> dict:
    return STAGES.get(number)


def get_all_stages_summary() -> list:
    """Return lightweight list of all stages with group info for the form selector."""
    return [
        {
            "number": s["number"],
            "short_name": s["short_name"],
            "applies_to": s["applies_to"],
            "group": s["group"],
        }
        for s in STAGES.values()
    ]


def get_stages_by_group() -> dict:
    """Return stages organised by group for the grouped form selector."""
    result = {}
    for group_name, stage_numbers in STAGE_GROUPS.items():
        result[group_name] = [
            {
                "number": STAGES[n]["number"],
                "short_name": STAGES[n]["short_name"],
                "applies_to": STAGES[n]["applies_to"],
            }
            for n in stage_numbers if n in STAGES
        ]
    return result


def photo_items_for_stage(stage_number: int) -> list:
    """Return all items for a stage (all have photos)."""
    stage = STAGES.get(stage_number, {})
    return [i for i in stage.get("items", []) if i.get("photo")]
